[colors.primary]
background = "#492731"
foreground = "#C0D1E4"
dim_foreground = "#A9B7C6"
bright_foreground = "#C0D1E4"

[colors.cursor]
text = "#492731"
cursor = "#C0D1E4"

[colors.vi_mode_cursor]
text = "#492731"
cursor = "#C0D1E4"

[colors.search.matches]
foreground = "#492731"
background = "#6B849D"

[colors.search.focused_match]
foreground = "#492731"
background = "#80b381"

[colors.footer_bar]
foreground = "#492731"
background = "#6B849D"

[colors.hints.start]
foreground = "#492731"
background = "#CCB366"

[colors.hints.end]
foreground = "#492731"
background = "#6B849D"

[colors.selection]
text = "#492731"
background = "#556B81"

[colors.normal]
black = "#6A3846"
red = "#CC6677"
green = "#80b381"
yellow = "#CCB366"
blue = "#6687CC"
magenta = "#c270a7"
cyan = "#66CBCC"
white = "#C0D1E4"

[colors.bright]
black = "#6A3846"
red = "#CC6677"
green = "#80b381"
yellow = "#CCB366"
blue = "#6687CC"
magenta = "#c270a7"
cyan = "#66CBCC"
white = "#C0D1E4"

[colors.dim]
black = "#6A3846"
red = "#CC6677"
green = "#80b381"
yellow = "#CCB366"
blue = "#6687CC"
magenta = "#c270a7"
cyan = "#66CBCC"
white = "#C0D1E4"