[colors.primary]
background = "#37615F"
foreground = "#D6F4DC"
dim_foreground = "#9DC7A7"
bright_foreground = "#D6F4DC"

[colors.cursor]
text = "#37615F"
cursor = "#D6F4DC"

[colors.vi_mode_cursor]
text = "#37615F"
cursor = "#D6F4DC"

[colors.search.matches]
foreground = "#37615F"
background = "#528792"

[colors.search.focused_match]
foreground = "#37615F"
background = "#88CC65"

[colors.footer_bar]
foreground = "#37615F"
background = "#528792"

[colors.hints.start]
foreground = "#37615F"
background = "#CCBA65"

[colors.hints.end]
foreground = "#37615F"
background = "#528792"

[colors.selection]
text = "#37615F"
background = "#497882"

[colors.normal]
black = "#24413F"
red = "#c08c8c"
green = "#88CC65"
yellow = "#CCBA65"
blue = "#7db3e8"
magenta = "#b48bc1"
cyan = "#65CCC9"
white = "#D6F4DC"

[colors.bright]
black = "#24413F"
red = "#c08c8c"
green = "#88CC65"
yellow = "#CCBA65"
blue = "#7db3e8"
magenta = "#b48bc1"
cyan = "#65CCC9"
white = "#D6F4DC"

[colors.dim]
black = "#24413F"
red = "#c08c8c"
green = "#88CC65"
yellow = "#CCBA65"
blue = "#7db3e8"
magenta = "#b48bc1"
cyan = "#65CCC9"
white = "#D6F4DC"