[colors.primary]
background = "#361721"
foreground = "#d3c2f0"
dim_foreground = "#9d82c9"
bright_foreground = "#d3c2f0"

[colors.cursor]
text = "#361721"
cursor = "#d3c2f0"

[colors.vi_mode_cursor]
text = "#361721"
cursor = "#d3c2f0"

[colors.search.matches]
foreground = "#361721"
background = "#6c5095"

[colors.search.focused_match]
foreground = "#361721"
background = "#b379ec"

[colors.footer_bar]
foreground = "#361721"
background = "#6c5095"

[colors.hints.start]
foreground = "#361721"
background = "#d98cb3"

[colors.hints.end]
foreground = "#361721"
background = "#6c5095"

[colors.selection]
text = "#361721"
background = "#543e74"

[colors.normal]
black = "#592636"
red = "#e87d7d"
green = "#b379ec"
yellow = "#d98cb3"
blue = "#9494d1"
magenta = "#8181e4"
cyan = "#d98cd9"
white = "#d3c2f0"

[colors.bright]
black = "#592636"
red = "#e87d7d"
green = "#b379ec"
yellow = "#d98cb3"
blue = "#9494d1"
magenta = "#8181e4"
cyan = "#d98cd9"
white = "#d3c2f0"

[colors.dim]
black = "#592636"
red = "#e87d7d"
green = "#b379ec"
yellow = "#d98cb3"
blue = "#9494d1"
magenta = "#8181e4"
cyan = "#d98cd9"
white = "#d3c2f0"