[colors.primary]
background = "#292D2C"
foreground = "#b4c7ca"
dim_foreground = "#82a0a6"
bright_foreground = "#b4c7ca"

[colors.cursor]
text = "#292D2C"
cursor = "#b4c7ca"

[colors.vi_mode_cursor]
text = "#292D2C"
cursor = "#b4c7ca"

[colors.search.matches]
foreground = "#292D2C"
background = "#6F7A67"

[colors.search.focused_match]
foreground = "#292D2C"
background = "#66CF82"

[colors.footer_bar]
foreground = "#292D2C"
background = "#6F7A67"

[colors.hints.start]
foreground = "#292D2C"
background = "#c4cb71"

[colors.hints.end]
foreground = "#292D2C"
background = "#6F7A67"

[colors.selection]
text = "#292D2C"
background = "#5E6757"

[colors.normal]
black = "#414845"
red = "#c86c85"
green = "#66CF82"
yellow = "#c4cb71"
blue = "#5B9BD6"
magenta = "#c669b5"
cyan = "#73c2b2"
white = "#b4c7ca"

[colors.bright]
black = "#414845"
red = "#c86c85"
green = "#66CF82"
yellow = "#c4cb71"
blue = "#5B9BD6"
magenta = "#c669b5"
cyan = "#73c2b2"
white = "#b4c7ca"

[colors.dim]
black = "#414845"
red = "#c86c85"
green = "#66CF82"
yellow = "#c4cb71"
blue = "#5B9BD6"
magenta = "#c669b5"
cyan = "#73c2b2"
white = "#b4c7ca"