[colors.primary]
background = "#272E2E"
foreground = "#A2E8D6"
dim_foreground = "#6FB3A2"
bright_foreground = "#A2E8D6"

[colors.cursor]
text = "#272E2E"
cursor = "#A2E8D6"

[colors.vi_mode_cursor]
text = "#272E2E"
cursor = "#A2E8D6"

[colors.search.matches]
foreground = "#272E2E"
background = "#58787D"

[colors.search.focused_match]
foreground = "#272E2E"
background = "#9fc653"

[colors.footer_bar]
foreground = "#272E2E"
background = "#58787D"

[colors.hints.start]
foreground = "#272E2E"
background = "#DFb06b"

[colors.hints.end]
foreground = "#272E2E"
background = "#58787D"

[colors.selection]
text = "#272E2E"
background = "#4D696D"

[colors.normal]
black = "#3F494A"
red = "#D74343"
green = "#9fc653"
yellow = "#DFb06b"
blue = "#679acc"
magenta = "#af5bc0"
cyan = "#5bc0bd"
white = "#A2E8D6"

[colors.bright]
black = "#3F494A"
red = "#D74343"
green = "#9fc653"
yellow = "#DFb06b"
blue = "#679acc"
magenta = "#af5bc0"
cyan = "#5bc0bd"
white = "#A2E8D6"

[colors.dim]
black = "#3F494A"
red = "#D74343"
green = "#9fc653"
yellow = "#DFb06b"
blue = "#679acc"
magenta = "#af5bc0"
cyan = "#5bc0bd"
white = "#A2E8D6"