[colors.primary]
background = "#3f3b31"
foreground = "#bfe3d7"
dim_foreground = "#A1CCBD"
bright_foreground = "#bfe3d7"

[colors.cursor]
text = "#3f3b31"
cursor = "#bfe3d7"

[colors.vi_mode_cursor]
text = "#3f3b31"
cursor = "#bfe3d7"

[colors.search.matches]
foreground = "#3f3b31"
background = "#6c9d8d"

[colors.search.focused_match]
foreground = "#3f3b31"
background = "#8bc198"

[colors.footer_bar]
foreground = "#3f3b31"
background = "#6c9d8d"

[colors.hints.start]
foreground = "#3f3b31"
background = "#d2af79"

[colors.hints.end]
foreground = "#3f3b31"
background = "#6c9d8d"

[colors.selection]
text = "#3f3b31"
background = "#568173"

[colors.normal]
black = "#5b5648"
red = "#c18b98"
green = "#8bc198"
yellow = "#d2af79"
blue = "#82a6c9"
magenta = "#c18bb3"
cyan = "#82c9c8"
white = "#bfe3d7"

[colors.bright]
black = "#5b5648"
red = "#c18b98"
green = "#8bc198"
yellow = "#d2af79"
blue = "#82a6c9"
magenta = "#c18bb3"
cyan = "#82c9c8"
white = "#bfe3d7"

[colors.dim]
black = "#5b5648"
red = "#c18b98"
green = "#8bc198"
yellow = "#d2af79"
blue = "#82a6c9"
magenta = "#c18bb3"
cyan = "#82c9c8"
white = "#bfe3d7"