[colors.primary]
background = "#181818"
foreground = "#DCE8F0"
dim_foreground = "#A2B5C2"
bright_foreground = "#DCE8F0"

[colors.cursor]
text = "#181818"
cursor = "#DCE8F0"

[colors.vi_mode_cursor]
text = "#181818"
cursor = "#DCE8F0"

[colors.search.matches]
foreground = "#181818"
background = "#666666"

[colors.search.focused_match]
foreground = "#181818"
background = "#90CB66"

[colors.footer_bar]
foreground = "#181818"
background = "#666666"

[colors.hints.start]
foreground = "#181818"
background = "#DFBE52"

[colors.hints.end]
foreground = "#181818"
background = "#666666"

[colors.selection]
text = "#181818"
background = "#4B4B4B"

[colors.normal]
black = "#333333"
red = "#CB6666"
green = "#90CB66"
yellow = "#DFBE52"
blue = "#667ECB"
magenta = "#C1709B"
cyan = "#66CBC3"
white = "#DCE8F0"

[colors.bright]
black = "#333333"
red = "#CB6666"
green = "#90CB66"
yellow = "#DFBE52"
blue = "#667ECB"
magenta = "#C1709B"
cyan = "#66CBC3"
white = "#DCE8F0"

[colors.dim]
black = "#333333"
red = "#CB6666"
green = "#90CB66"
yellow = "#DFBE52"
blue = "#667ECB"
magenta = "#C1709B"
cyan = "#66CBC3"
white = "#DCE8F0"