[colors.primary]
background = "#394230"
foreground = "#C2E0E0"
dim_foreground = "#B0C1C1"
bright_foreground = "#C2E0E0"

[colors.cursor]
text = "#394230"
cursor = "#C2E0E0"

[colors.vi_mode_cursor]
text = "#394230"
cursor = "#C2E0E0"

[colors.search.matches]
foreground = "#394230"
background = "#799595"

[colors.search.focused_match]
foreground = "#394230"
background = "#B2E083"

[colors.footer_bar]
foreground = "#394230"
background = "#799595"

[colors.hints.start]
foreground = "#394230"
background = "#E0C983"

[colors.hints.end]
foreground = "#394230"
background = "#799595"

[colors.selection]
text = "#394230"
background = "#5F7878"

[colors.normal]
black = "#525f45"
red = "#d98cac"
green = "#B2E083"
yellow = "#E0C983"
blue = "#8cb3d9"
magenta = "#c18cd9"
cyan = "#8cd9d9"
white = "#C2E0E0"

[colors.bright]
black = "#525f45"
red = "#d98cac"
green = "#B2E083"
yellow = "#E0C983"
blue = "#8cb3d9"
magenta = "#c18cd9"
cyan = "#8cd9d9"
white = "#C2E0E0"

[colors.dim]
black = "#525f45"
red = "#d98cac"
green = "#B2E083"
yellow = "#E0C983"
blue = "#8cb3d9"
magenta = "#c18cd9"
cyan = "#8cd9d9"
white = "#C2E0E0"