[colors.primary]
background = "#2D4531"
foreground = "#B5EDED"
dim_foreground = "#AAC7C7"
bright_foreground = "#B5EDED"

[colors.cursor]
text = "#2D4531"
cursor = "#B5EDED"

[colors.vi_mode_cursor]
text = "#2D4531"
cursor = "#B5EDED"

[colors.search.matches]
foreground = "#2D4531"
background = "#6F9F9F"

[colors.search.focused_match]
foreground = "#2D4531"
background = "#99C769"

[colors.footer_bar]
foreground = "#2D4531"
background = "#6F9F9F"

[colors.hints.start]
foreground = "#2D4531"
background = "#CC9166"

[colors.hints.end]
foreground = "#2D4531"
background = "#6F9F9F"

[colors.selection]
text = "#2D4531"
background = "#568181"

[colors.normal]
black = "#416146"
red = "#C27193"
green = "#99C769"
yellow = "#CC9166"
blue = "#6BB7C7"
magenta = "#A670C1"
cyan = "#6DC792"
white = "#B5EDED"

[colors.bright]
black = "#416146"
red = "#C27193"
green = "#99C769"
yellow = "#CC9166"
blue = "#6BB7C7"
magenta = "#A670C1"
cyan = "#6DC792"
white = "#B5EDED"

[colors.dim]
black = "#416146"
red = "#C27193"
green = "#99C769"
yellow = "#CC9166"
blue = "#6BB7C7"
magenta = "#A670C1"
cyan = "#6DC792"
white = "#B5EDED"