[colors.primary]
background = "#272923"
foreground = "#b4e2ee"
dim_foreground = "#abbfc4"
bright_foreground = "#b4e2ee"

[colors.cursor]
text = "#272923"
cursor = "#b4e2ee"

[colors.vi_mode_cursor]
text = "#272923"
cursor = "#b4e2ee"

[colors.search.matches]
foreground = "#272923"
background = "#5E7E87"

[colors.search.focused_match]
foreground = "#272923"
background = "#93D0A2"

[colors.footer_bar]
foreground = "#272923"
background = "#5E7E87"

[colors.hints.start]
foreground = "#272923"
background = "#DCD587"

[colors.hints.end]
foreground = "#272923"
background = "#5E7E87"

[colors.selection]
text = "#272923"
background = "#496269"

[colors.normal]
black = "#43443A"
red = "#DC8896"
green = "#93D0A2"
yellow = "#DCD587"
blue = "#9398D0"
magenta = "#C193D1"
cyan = "#93B2D0"
white = "#b4e2ee"

[colors.bright]
black = "#43443A"
red = "#DC8896"
green = "#93D0A2"
yellow = "#DCD587"
blue = "#9398D0"
magenta = "#C193D1"
cyan = "#93B2D0"
white = "#b4e2ee"

[colors.dim]
black = "#43443A"
red = "#DC8896"
green = "#93D0A2"
yellow = "#DCD587"
blue = "#9398D0"
magenta = "#C193D1"
cyan = "#93B2D0"
white = "#b4e2ee"