[colors.primary]
background = "#3a3d34"
foreground = "#b4e2ee"
dim_foreground = "#abbfc4"
bright_foreground = "#b4e2ee"

[colors.cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.vi_mode_cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.search.matches]
foreground = "#3a3d34"
background = "#6f919b"

[colors.search.focused_match]
foreground = "#3a3d34"
background = "#82C9AB"

[colors.footer_bar]
foreground = "#3a3d34"
background = "#6f919b"

[colors.hints.start]
foreground = "#3a3d34"
background = "#D6CE74"

[colors.hints.end]
foreground = "#3a3d34"
background = "#6f919b"

[colors.selection]
text = "#3a3d34"
background = "#58767e"

[colors.normal]
black = "#55584b"
red = "#C98288"
green = "#82C9AB"
yellow = "#D6CE74"
blue = "#9098D4"
magenta = "#CF90D4"
cyan = "#86B0C4"
white = "#b4e2ee"

[colors.bright]
black = "#55584b"
red = "#C98288"
green = "#82C9AB"
yellow = "#D6CE74"
blue = "#9098D4"
magenta = "#CF90D4"
cyan = "#86B0C4"
white = "#b4e2ee"

[colors.dim]
black = "#55584b"
red = "#C98288"
green = "#82C9AB"
yellow = "#D6CE74"
blue = "#9098D4"
magenta = "#CF90D4"
cyan = "#86B0C4"
white = "#b4e2ee"