[colors.primary]
background = "#3a3d34"
foreground = "#b4e2ee"
dim_foreground = "#abbfc4"
bright_foreground = "#b4e2ee"

[colors.cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.vi_mode_cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.search.matches]
foreground = "#3a3d34"
background = "#6f919b"

[colors.search.focused_match]
foreground = "#3a3d34"
background = "#93D0A2"

[colors.footer_bar]
foreground = "#3a3d34"
background = "#6f919b"

[colors.hints.start]
foreground = "#3a3d34"
background = "#DCD587"

[colors.hints.end]
foreground = "#3a3d34"
background = "#6f919b"

[colors.selection]
text = "#3a3d34"
background = "#58767e"

[colors.normal]
black = "#55584b"
red = "#DC8896"
green = "#93D0A2"
yellow = "#DCD587"
blue = "#9398D0"
magenta = "#C193D1"
cyan = "#93B2D0"
white = "#b4e2ee"

[colors.bright]
black = "#55584b"
red = "#DC8896"
green = "#93D0A2"
yellow = "#DCD587"
blue = "#9398D0"
magenta = "#C193D1"
cyan = "#93B2D0"
white = "#b4e2ee"

[colors.dim]
black = "#55584b"
red = "#DC8896"
green = "#93D0A2"
yellow = "#DCD587"
blue = "#9398D0"
magenta = "#C193D1"
cyan = "#93B2D0"
white = "#b4e2ee"