[colors.primary]
background = "#2E272E"
foreground = "#C4F4A2"
dim_foreground = "#9DB779"
bright_foreground = "#C4F4A2"

[colors.cursor]
text = "#2E272E"
cursor = "#C4F4A2"

[colors.vi_mode_cursor]
text = "#2E272E"
cursor = "#C4F4A2"

[colors.search.matches]
foreground = "#2E272E"
background = "#798569"

[colors.search.focused_match]
foreground = "#2E272E"
background = "#96C486"

[colors.footer_bar]
foreground = "#2E272E"
background = "#798569"

[colors.hints.start]
foreground = "#2E272E"
background = "#D6985B"

[colors.hints.end]
foreground = "#2E272E"
background = "#798569"

[colors.selection]
text = "#2E272E"
background = "#6C775E"

[colors.normal]
black = "#493F4A"
red = "#C1707B"
green = "#96C486"
yellow = "#D6985B"
blue = "#70A3C1"
magenta = "#B375BC"
cyan = "#86C4AA"
white = "#C4F4A2"

[colors.bright]
black = "#493F4A"
red = "#C1707B"
green = "#96C486"
yellow = "#D6985B"
blue = "#70A3C1"
magenta = "#B375BC"
cyan = "#86C4AA"
white = "#C4F4A2"

[colors.dim]
black = "#493F4A"
red = "#C1707B"
green = "#96C486"
yellow = "#D6985B"
blue = "#70A3C1"
magenta = "#B375BC"
cyan = "#86C4AA"
white = "#C4F4A2"