[colors.primary]
background = "#1F212D"
foreground = "#DFD1DF"
dim_foreground = "#B595B5"
bright_foreground = "#DFD1DF"

[colors.cursor]
text = "#1F212D"
cursor = "#DFD1DF"

[colors.vi_mode_cursor]
text = "#1F212D"
cursor = "#DFD1DF"

[colors.search.matches]
foreground = "#1F212D"
background = "#875E87"

[colors.search.focused_match]
foreground = "#1F212D"
background = "#bed775"

[colors.footer_bar]
foreground = "#1F212D"
background = "#875E87"

[colors.hints.start]
foreground = "#1F212D"
background = "#eccf79"

[colors.hints.end]
foreground = "#1F212D"
background = "#875E87"

[colors.selection]
text = "#1F212D"
background = "#694969"

[colors.normal]
black = "#34374B"
red = "#e06c6c"
green = "#bed775"
yellow = "#eccf79"
blue = "#79d2d2"
magenta = "#d874a6"
cyan = "#74d88d"
white = "#DFD1DF"

[colors.bright]
black = "#34374B"
red = "#e06c6c"
green = "#bed775"
yellow = "#eccf79"
blue = "#79d2d2"
magenta = "#d874a6"
cyan = "#74d88d"
white = "#DFD1DF"

[colors.dim]
black = "#34374B"
red = "#e06c6c"
green = "#bed775"
yellow = "#eccf79"
blue = "#79d2d2"
magenta = "#d874a6"
cyan = "#74d88d"
white = "#DFD1DF"