[colors.primary]
background = "#292329"
foreground = "#eec4ee"
dim_foreground = "#b497b4"
bright_foreground = "#eec4ee"

[colors.cursor]
text = "#292329"
cursor = "#eec4ee"

[colors.vi_mode_cursor]
text = "#292329"
cursor = "#eec4ee"

[colors.search.matches]
foreground = "#292329"
background = "#7c6a7c"

[colors.search.focused_match]
foreground = "#292329"
background = "#c2d194"

[colors.footer_bar]
foreground = "#292329"
background = "#7c6a7c"

[colors.hints.start]
foreground = "#292329"
background = "#e09c85"

[colors.hints.end]
foreground = "#292329"
background = "#7c6a7c"

[colors.selection]
text = "#292329"
background = "#605260"

[colors.normal]
black = "#453b45"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#eec4ee"

[colors.bright]
black = "#453b45"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#eec4ee"

[colors.dim]
black = "#453b45"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#eec4ee"