[colors.primary]
background = "#0f1a24"
foreground = "#b8cce0"
dim_foreground = "#859aad"
bright_foreground = "#b8cce0"

[colors.cursor]
text = "#0f1a24"
cursor = "#b8cce0"

[colors.vi_mode_cursor]
text = "#0f1a24"
cursor = "#b8cce0"

[colors.search.matches]
foreground = "#0f1a24"
background = "#52677a"

[colors.search.focused_match]
foreground = "#0f1a24"
background = "#A6D279"

[colors.footer_bar]
foreground = "#0f1a24"
background = "#52677a"

[colors.hints.start]
foreground = "#0f1a24"
background = "#DBDB70"

[colors.hints.end]
foreground = "#0f1a24"
background = "#52677a"

[colors.selection]
text = "#0f1a24"
background = "#3d4d5c"

[colors.normal]
black = "#1f3347"
red = "#D279A6"
green = "#A6D279"
yellow = "#DBDB70"
blue = "#79BBD2"
magenta = "#7878D2"
cyan = "#79D2A6"
white = "#b8cce0"

[colors.bright]
black = "#1f3347"
red = "#D279A6"
green = "#A6D279"
yellow = "#DBDB70"
blue = "#79BBD2"
magenta = "#7878D2"
cyan = "#79D2A6"
white = "#b8cce0"

[colors.dim]
black = "#1f3347"
red = "#D279A6"
green = "#A6D279"
yellow = "#DBDB70"
blue = "#79BBD2"
magenta = "#7878D2"
cyan = "#79D2A6"
white = "#b8cce0"