[colors.primary]
background = "#1d3026"
foreground = "#cfe2d8"
dim_foreground = "#8fbca4"
bright_foreground = "#cfe2d8"

[colors.cursor]
text = "#1d3026"
cursor = "#cfe2d8"

[colors.vi_mode_cursor]
text = "#1d3026"
cursor = "#cfe2d8"

[colors.search.matches]
foreground = "#1d3026"
background = "#568f71"

[colors.search.focused_match]
foreground = "#1d3026"
background = "#95d0d0"

[colors.footer_bar]
foreground = "#1d3026"
background = "#568f71"

[colors.hints.start]
foreground = "#1d3026"
background = "#8cd9b3"

[colors.hints.end]
foreground = "#1d3026"
background = "#568f71"

[colors.selection]
text = "#1d3026"
background = "#437058"

[colors.normal]
black = "#30503f"
red = "#75f09e"
green = "#95d0d0"
yellow = "#8cd9b3"
blue = "#c4e87d"
magenta = "#cccc99"
cyan = "#8cd98c"
white = "#cfe2d8"

[colors.bright]
black = "#30503f"
red = "#75f09e"
green = "#95d0d0"
yellow = "#8cd9b3"
blue = "#c4e87d"
magenta = "#cccc99"
cyan = "#8cd98c"
white = "#cfe2d8"

[colors.dim]
black = "#30503f"
red = "#75f09e"
green = "#95d0d0"
yellow = "#8cd9b3"
blue = "#c4e87d"
magenta = "#cccc99"
cyan = "#8cd98c"
white = "#cfe2d8"