[colors.primary]
background = "#cee4ce"
foreground = "#2c3a2c"
dim_foreground = "#587458"
bright_foreground = "#2c3a2c"

[colors.cursor]
text = "#cee4ce"
cursor = "#2c3a2c"

[colors.vi_mode_cursor]
text = "#cee4ce"
cursor = "#2c3a2c"

[colors.search.matches]
foreground = "#cee4ce"
background = "#8aa88a"

[colors.search.focused_match]
foreground = "#cee4ce"
background = "#2d8659"

[colors.footer_bar]
foreground = "#cee4ce"
background = "#8aa88a"

[colors.hints.start]
foreground = "#cee4ce"
background = "#267326"

[colors.hints.end]
foreground = "#cee4ce"
background = "#8aa88a"

[colors.selection]
text = "#cee4ce"
background = "#98b398"

[colors.normal]
black = "#add2ad"
red = "#0f8a38"
green = "#2d8659"
yellow = "#267326"
blue = "#5e8217"
magenta = "#77773c"
cyan = "#006666"
white = "#2c3a2c"

[colors.bright]
black = "#add2ad"
red = "#0f8a38"
green = "#2d8659"
yellow = "#267326"
blue = "#5e8217"
magenta = "#77773c"
cyan = "#006666"
white = "#2c3a2c"

[colors.dim]
black = "#add2ad"
red = "#0f8a38"
green = "#2d8659"
yellow = "#267326"
blue = "#5e8217"
magenta = "#77773c"
cyan = "#006666"
white = "#2c3a2c"