[colors.primary]
background = "#1d3026"
foreground = "#cfe2d8"
dim_foreground = "#8fbca4"
bright_foreground = "#cfe2d8"

[colors.cursor]
text = "#1d3026"
cursor = "#cfe2d8"

[colors.vi_mode_cursor]
text = "#1d3026"
cursor = "#cfe2d8"

[colors.search.matches]
foreground = "#1d3026"
background = "#568f71"

[colors.search.focused_match]
foreground = "#1d3026"
background = "#95d0d0"

[colors.footer_bar]
foreground = "#1d3026"
background = "#568f71"

[colors.hints.start]
foreground = "#1d3026"
background = "#c4e87d"

[colors.hints.end]
foreground = "#1d3026"
background = "#568f71"

[colors.selection]
text = "#1d3026"
background = "#437058"

[colors.normal]
black = "#264032"
red = "#75f09e"
green = "#95d0d0"
yellow = "#8cd98c"
blue = "#cccc99"
magenta = "#c4e87d"
cyan = "#8cd9b3"
white = "#cfe2d8"

[colors.bright]
black = "#30503f"
red = "#a3f5be"
green = "#b8e0e0"
yellow = "#b3e6b3"
blue = "#ddddbb"
magenta = "#d8f0a8"
cyan = "#b3e6cc"
white = "#8fbca4"

[colors.dim]
black = "#30503f"
red = "#a3f5be"
green = "#b8e0e0"
yellow = "#b3e6b3"
blue = "#ddddbb"
magenta = "#d8f0a8"
cyan = "#b3e6cc"
white = "#8fbca4"