[colors.primary]
background = "#000000"
foreground = "#ffffff"
dim_foreground = "#999999"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#000000"
background = "#666666"

[colors.search.focused_match]
foreground = "#000000"
background = "#00ff00"

[colors.footer_bar]
foreground = "#000000"
background = "#666666"

[colors.hints.start]
foreground = "#000000"
background = "#ff00ff"

[colors.hints.end]
foreground = "#000000"
background = "#666666"

[colors.selection]
text = "#000000"
background = "#4d4d4d"

[colors.normal]
black = "#1a1a1a"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0080ff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[colors.bright]
black = "#333333"
red = "#ff9999"
green = "#99ff99"
yellow = "#ffff99"
blue = "#99ccff"
magenta = "#ff99ff"
cyan = "#99ffff"
white = "#999999"

[colors.dim]
black = "#333333"
red = "#ff9999"
green = "#99ff99"
yellow = "#ffff99"
blue = "#99ccff"
magenta = "#ff99ff"
cyan = "#99ffff"
white = "#999999"