[colors.primary]
background = "#000000"
foreground = "#ffffff"
dim_foreground = "#999999"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#000000"
background = "#666666"

[colors.search.focused_match]
foreground = "#000000"
background = "#00ff00"

[colors.footer_bar]
foreground = "#000000"
background = "#666666"

[colors.hints.start]
foreground = "#000000"
background = "#00ffff"

[colors.hints.end]
foreground = "#000000"
background = "#666666"

[colors.selection]
text = "#000000"
background = "#4d4d4d"

[colors.normal]
black = "#333333"
red = "#ff0000"
green = "#00ff00"
yellow = "#00ffff"
blue = "#ff00ff"
magenta = "#0080ff"
cyan = "#ffff00"
white = "#ffffff"

[colors.bright]
black = "#333333"
red = "#ff0000"
green = "#00ff00"
yellow = "#00ffff"
blue = "#ff00ff"
magenta = "#0080ff"
cyan = "#ffff00"
white = "#ffffff"

[colors.dim]
black = "#333333"
red = "#ff0000"
green = "#00ff00"
yellow = "#00ffff"
blue = "#ff00ff"
magenta = "#0080ff"
cyan = "#ffff00"
white = "#ffffff"