[colors.primary]
background = "#1a1a1a"
foreground = "#f2f2f2"
dim_foreground = "#a6a6a6"
bright_foreground = "#f2f2f2"

[colors.cursor]
text = "#1a1a1a"
cursor = "#f2f2f2"

[colors.vi_mode_cursor]
text = "#1a1a1a"
cursor = "#f2f2f2"

[colors.search.matches]
foreground = "#1a1a1a"
background = "#666666"

[colors.search.focused_match]
foreground = "#1a1a1a"
background = "#eded5e"

[colors.footer_bar]
foreground = "#1a1a1a"
background = "#666666"

[colors.hints.start]
foreground = "#1a1a1a"
background = "#eda65e"

[colors.hints.end]
foreground = "#1a1a1a"
background = "#666666"

[colors.selection]
text = "#1a1a1a"
background = "#4d4d4d"

[colors.normal]
black = "#262626"
red = "#5e5eed"
green = "#eded5e"
yellow = "#5eeded"
blue = "#5ea6ed"
magenta = "#eda65e"
cyan = "#5eed5e"
white = "#f2f2f2"

[colors.bright]
black = "#333333"
red = "#8c8cf2"
green = "#f2f28c"
yellow = "#8cf2f2"
blue = "#8cbff2"
magenta = "#f2bf8c"
cyan = "#8cf28c"
white = "#a6a6a6"

[colors.dim]
black = "#333333"
red = "#8c8cf2"
green = "#f2f28c"
yellow = "#8cf2f2"
blue = "#8cbff2"
magenta = "#f2bf8c"
cyan = "#8cf28c"
white = "#a6a6a6"