[colors.primary]
background = "#1a1a1a"
foreground = "#f2f2f2"
dim_foreground = "#a6a6a6"
bright_foreground = "#f2f2f2"

[colors.cursor]
text = "#1a1a1a"
cursor = "#f2f2f2"

[colors.vi_mode_cursor]
text = "#1a1a1a"
cursor = "#f2f2f2"

[colors.search.matches]
foreground = "#1a1a1a"
background = "#666666"

[colors.search.focused_match]
foreground = "#1a1a1a"
background = "#eded5e"

[colors.footer_bar]
foreground = "#1a1a1a"
background = "#666666"

[colors.hints.start]
foreground = "#1a1a1a"
background = "#5eed5e"

[colors.hints.end]
foreground = "#1a1a1a"
background = "#666666"

[colors.selection]
text = "#1a1a1a"
background = "#4d4d4d"

[colors.normal]
black = "#333333"
red = "#5e5eed"
green = "#eded5e"
yellow = "#5eed5e"
blue = "#eda65e"
magenta = "#5ea6ed"
cyan = "#5eeded"
white = "#f2f2f2"

[colors.bright]
black = "#333333"
red = "#5e5eed"
green = "#eded5e"
yellow = "#5eed5e"
blue = "#eda65e"
magenta = "#5ea6ed"
cyan = "#5eeded"
white = "#f2f2f2"

[colors.dim]
black = "#333333"
red = "#5e5eed"
green = "#eded5e"
yellow = "#5eed5e"
blue = "#eda65e"
magenta = "#5ea6ed"
cyan = "#5eeded"
white = "#f2f2f2"