[colors.primary]
background = "#303127"
foreground = "#E4E2C5"
dim_foreground = "#B3B18B"
bright_foreground = "#E4E2C5"

[colors.cursor]
text = "#303127"
cursor = "#E4E2C5"

[colors.vi_mode_cursor]
text = "#303127"
cursor = "#E4E2C5"

[colors.search.matches]
foreground = "#303127"
background = "#7B7F68"

[colors.search.focused_match]
foreground = "#303127"
background = "#B3C271"

[colors.footer_bar]
foreground = "#303127"
background = "#7B7F68"

[colors.hints.start]
foreground = "#303127"
background = "#DAA655"

[colors.hints.end]
foreground = "#303127"
background = "#7B7F68"

[colors.selection]
text = "#303127"
background = "#686B58"

[colors.normal]
black = "#4A4E3E"
red = "#C17670"
green = "#B3C271"
yellow = "#DAA655"
blue = "#6F8BC1"
magenta = "#C170A4"
cyan = "#71B7C1"
white = "#E4E2C5"

[colors.bright]
black = "#4A4E3E"
red = "#C17670"
green = "#B3C271"
yellow = "#DAA655"
blue = "#6F8BC1"
magenta = "#C170A4"
cyan = "#71B7C1"
white = "#E4E2C5"

[colors.dim]
black = "#4A4E3E"
red = "#C17670"
green = "#B3C271"
yellow = "#DAA655"
blue = "#6F8BC1"
magenta = "#C170A4"
cyan = "#71B7C1"
white = "#E4E2C5"