[colors.primary]
background = "#191221"
foreground = "#BCDBC4"
dim_foreground = "#89A891"
bright_foreground = "#BCDBC4"

[colors.cursor]
text = "#191221"
cursor = "#BCDBC4"

[colors.vi_mode_cursor]
text = "#191221"
cursor = "#BCDBC4"

[colors.search.matches]
foreground = "#191221"
background = "#56755E"

[colors.search.focused_match]
foreground = "#191221"
background = "#66cc99"

[colors.footer_bar]
foreground = "#191221"
background = "#56755E"

[colors.hints.start]
foreground = "#191221"
background = "#bcd279"

[colors.hints.end]
foreground = "#191221"
background = "#56755E"

[colors.selection]
text = "#191221"
background = "#415746"

[colors.normal]
black = "#322442"
red = "#cc6666"
green = "#66cc99"
yellow = "#bcd279"
blue = "#a682c9"
magenta = "#d194b3"
cyan = "#82c9c9"
white = "#BCDBC4"

[colors.bright]
black = "#322442"
red = "#cc6666"
green = "#66cc99"
yellow = "#bcd279"
blue = "#a682c9"
magenta = "#d194b3"
cyan = "#82c9c9"
white = "#BCDBC4"

[colors.dim]
black = "#322442"
red = "#cc6666"
green = "#66cc99"
yellow = "#bcd279"
blue = "#a682c9"
magenta = "#d194b3"
cyan = "#82c9c9"
white = "#BCDBC4"