[colors.primary]
background = "#191221"
foreground = "#bddbc5"
dim_foreground = "#7ab88a"
bright_foreground = "#bddbc5"

[colors.cursor]
text = "#191221"
cursor = "#bddbc5"

[colors.vi_mode_cursor]
text = "#191221"
cursor = "#bddbc5"

[colors.search.matches]
foreground = "#191221"
background = "#527a5c"

[colors.search.focused_match]
foreground = "#191221"
background = "#66cc99"

[colors.footer_bar]
foreground = "#191221"
background = "#527a5c"

[colors.hints.start]
foreground = "#191221"
background = "#bcd279"

[colors.hints.end]
foreground = "#191221"
background = "#527a5c"

[colors.selection]
text = "#191221"
background = "#3d5c45"

[colors.normal]
black = "#322442"
red = "#cc6666"
green = "#66cc99"
yellow = "#bcd279"
blue = "#a682c9"
magenta = "#d194b3"
cyan = "#82c9c9"
white = "#bddbc5"

[colors.bright]
black = "#322442"
red = "#cc6666"
green = "#66cc99"
yellow = "#bcd279"
blue = "#a682c9"
magenta = "#d194b3"
cyan = "#82c9c9"
white = "#bddbc5"

[colors.dim]
black = "#322442"
red = "#cc6666"
green = "#66cc99"
yellow = "#bcd279"
blue = "#a682c9"
magenta = "#d194b3"
cyan = "#82c9c9"
white = "#bddbc5"