[colors.primary]
background = "#493327"
foreground = "#C4D6DF"
dim_foreground = "#B1BABF"
bright_foreground = "#C4D6DF"

[colors.cursor]
text = "#493327"
cursor = "#C4D6DF"

[colors.vi_mode_cursor]
text = "#493327"
cursor = "#C4D6DF"

[colors.search.matches]
foreground = "#493327"
background = "#788890"

[colors.search.focused_match]
foreground = "#493327"
background = "#6AAE6E"

[colors.footer_bar]
foreground = "#493327"
background = "#788890"

[colors.hints.start]
foreground = "#493327"
background = "#C08459"

[colors.hints.end]
foreground = "#493327"
background = "#788890"

[colors.selection]
text = "#493327"
background = "#606E75"

[colors.normal]
black = "#6A4A38"
red = "#BA5F78"
green = "#6AAE6E"
yellow = "#C08459"
blue = "#5F76BB"
magenta = "#AF6AAF"
cyan = "#6AAFAD"
white = "#C4D6DF"

[colors.bright]
black = "#6A4A38"
red = "#BA5F78"
green = "#6AAE6E"
yellow = "#C08459"
blue = "#5F76BB"
magenta = "#AF6AAF"
cyan = "#6AAFAD"
white = "#C4D6DF"

[colors.dim]
black = "#6A4A38"
red = "#BA5F78"
green = "#6AAE6E"
yellow = "#C08459"
blue = "#5F76BB"
magenta = "#AF6AAF"
cyan = "#6AAFAD"
white = "#C4D6DF"