[colors.primary]
background = "#312928"
foreground = "#B6CBD8"
dim_foreground = "#8A979F"
bright_foreground = "#B6CBD8"

[colors.cursor]
text = "#312928"
cursor = "#B6CBD8"

[colors.vi_mode_cursor]
text = "#312928"
cursor = "#B6CBD8"

[colors.search.matches]
foreground = "#312928"
background = "#65737C"

[colors.search.focused_match]
foreground = "#312928"
background = "#8CAB5D"

[colors.footer_bar]
foreground = "#312928"
background = "#65737C"

[colors.hints.start]
foreground = "#312928"
background = "#E4C468"

[colors.hints.end]
foreground = "#312928"
background = "#65737C"

[colors.selection]
text = "#312928"
background = "#546067"

[colors.normal]
black = "#4B3F3E"
red = "#AF6875"
green = "#8CAB5D"
yellow = "#E4C468"
blue = "#8879B8"
magenta = "#AE79B8"
cyan = "#59A57F"
white = "#B6CBD8"

[colors.bright]
black = "#4B3F3E"
red = "#AF6875"
green = "#8CAB5D"
yellow = "#E4C468"
blue = "#8879B8"
magenta = "#AE79B8"
cyan = "#59A57F"
white = "#B6CBD8"

[colors.dim]
black = "#4B3F3E"
red = "#AF6875"
green = "#8CAB5D"
yellow = "#E4C468"
blue = "#8879B8"
magenta = "#AE79B8"
cyan = "#59A57F"
white = "#B6CBD8"