[colors.primary]
background = "#5B6335"
foreground = "#EFF4D6"
dim_foreground = "#C1C99B"
bright_foreground = "#EFF4D6"

[colors.cursor]
text = "#5B6335"
cursor = "#EFF4D6"

[colors.vi_mode_cursor]
text = "#5B6335"
cursor = "#EFF4D6"

[colors.search.matches]
foreground = "#5B6335"
background = "#98A559"

[colors.search.focused_match]
foreground = "#5B6335"
background = "#6BC673"

[colors.footer_bar]
foreground = "#5B6335"
background = "#98A559"

[colors.hints.start]
foreground = "#5B6335"
background = "#CCC265"

[colors.hints.end]
foreground = "#5B6335"
background = "#98A559"

[colors.selection]
text = "#5B6335"
background = "#798447"

[colors.normal]
black = "#3C4223"
red = "#B77A8F"
green = "#6BC673"
yellow = "#CCC265"
blue = "#6B82C6"
magenta = "#A37AB7"
cyan = "#70BFC1"
white = "#EFF4D6"

[colors.bright]
black = "#3C4223"
red = "#B77A8F"
green = "#6BC673"
yellow = "#CCC265"
blue = "#6B82C6"
magenta = "#A37AB7"
cyan = "#70BFC1"
white = "#EFF4D6"

[colors.dim]
black = "#3C4223"
red = "#B77A8F"
green = "#6BC673"
yellow = "#CCC265"
blue = "#6B82C6"
magenta = "#A37AB7"
cyan = "#70BFC1"
white = "#EFF4D6"