[colors.primary]
background = "#1F202D"
foreground = "#E4E0CD"
dim_foreground = "#C0B78A"
bright_foreground = "#E4E0CD"

[colors.cursor]
text = "#1F202D"
cursor = "#E4E0CD"

[colors.vi_mode_cursor]
text = "#1F202D"
cursor = "#E4E0CD"

[colors.search.matches]
foreground = "#1F202D"
background = "#958950"

[colors.search.focused_match]
foreground = "#1F202D"
background = "#C1C271"

[colors.footer_bar]
foreground = "#1F202D"
background = "#958950"

[colors.hints.start]
foreground = "#1F202D"
background = "#CBA165"

[colors.hints.end]
foreground = "#1F202D"
background = "#958950"

[colors.selection]
text = "#1F202D"
background = "#746A3E"

[colors.normal]
black = "#34364B"
red = "#CC6575"
green = "#C1C271"
yellow = "#CBA165"
blue = "#688FCC"
magenta = "#B07AB7"
cyan = "#70C2B8"
white = "#E4E0CD"

[colors.bright]
black = "#34364B"
red = "#CC6575"
green = "#C1C271"
yellow = "#CBA165"
blue = "#688FCC"
magenta = "#B07AB7"
cyan = "#70C2B8"
white = "#E4E0CD"

[colors.dim]
black = "#34364B"
red = "#CC6575"
green = "#C1C271"
yellow = "#CBA165"
blue = "#688FCC"
magenta = "#B07AB7"
cyan = "#70C2B8"
white = "#E4E0CD"