[colors.primary]
background = "#435155"
foreground = "#DAE3EF"
dim_foreground = "#93AED1"
bright_foreground = "#DAE3EF"

[colors.cursor]
text = "#435155"
cursor = "#DAE3EF"

[colors.vi_mode_cursor]
text = "#435155"
cursor = "#DAE3EF"

[colors.search.matches]
foreground = "#435155"
background = "#647A80"

[colors.search.focused_match]
foreground = "#435155"
background = "#94c982"

[colors.footer_bar]
foreground = "#435155"
background = "#647A80"

[colors.hints.start]
foreground = "#435155"
background = "#d5d590"

[colors.hints.end]
foreground = "#435155"
background = "#647A80"

[colors.selection]
text = "#435155"
background = "#596C72"

[colors.normal]
black = "#2C3639"
red = "#ce7e7e"
green = "#94c982"
yellow = "#d5d590"
blue = "#79bcd2"
magenta = "#be94d1"
cyan = "#90d5c4"
white = "#DAE3EF"

[colors.bright]
black = "#2C3639"
red = "#ce7e7e"
green = "#94c982"
yellow = "#d5d590"
blue = "#79bcd2"
magenta = "#be94d1"
cyan = "#90d5c4"
white = "#DAE3EF"

[colors.dim]
black = "#2C3639"
red = "#ce7e7e"
green = "#94c982"
yellow = "#d5d590"
blue = "#79bcd2"
magenta = "#be94d1"
cyan = "#90d5c4"
white = "#DAE3EF"