[colors.primary]
background = "#5E7278"
foreground = "#DAE3EF"
dim_foreground = "#94AFD2"
bright_foreground = "#DAE3EF"

[colors.cursor]
text = "#5E7278"
cursor = "#DAE3EF"

[colors.vi_mode_cursor]
text = "#5E7278"
cursor = "#DAE3EF"

[colors.search.matches]
foreground = "#5E7278"
background = "#48585C"

[colors.search.focused_match]
foreground = "#5E7278"
background = "#94c982"

[colors.footer_bar]
foreground = "#5E7278"
background = "#48585C"

[colors.hints.start]
foreground = "#5E7278"
background = "#d5d590"

[colors.hints.end]
foreground = "#5E7278"
background = "#48585C"

[colors.selection]
text = "#5E7278"
background = "#526469"

[colors.normal]
black = "#768E94"
red = "#ce7e7e"
green = "#94c982"
yellow = "#d5d590"
blue = "#79bcd2"
magenta = "#be94d1"
cyan = "#90d5c4"
white = "#DAE3EF"

[colors.bright]
black = "#768E94"
red = "#ce7e7e"
green = "#94c982"
yellow = "#d5d590"
blue = "#79bcd2"
magenta = "#be94d1"
cyan = "#90d5c4"
white = "#DAE3EF"

[colors.dim]
black = "#768E94"
red = "#ce7e7e"
green = "#94c982"
yellow = "#d5d590"
blue = "#79bcd2"
magenta = "#be94d1"
cyan = "#90d5c4"
white = "#DAE3EF"