[colors.primary]
background = "#ada384"
foreground = "#1a2633"
dim_foreground = "#323f4c"
bright_foreground = "#1a2633"

[colors.cursor]
text = "#ada384"
cursor = "#1a2633"

[colors.vi_mode_cursor]
text = "#ada384"
cursor = "#1a2633"

[colors.search.matches]
foreground = "#ada384"
background = "#cac3af"

[colors.search.focused_match]
foreground = "#ada384"
background = "#367d4e"

[colors.footer_bar]
foreground = "#ada384"
background = "#cac3af"

[colors.hints.start]
foreground = "#ada384"
background = "#996f33"

[colors.hints.end]
foreground = "#ada384"
background = "#cac3af"

[colors.selection]
text = "#ada384"
background = "#bcb39a"

[colors.normal]
black = "#998e67"
red = "#7d364e"
green = "#367d4e"
yellow = "#996f33"
blue = "#2d4386"
magenta = "#7d366b"
cyan = "#2d8684"
white = "#1a2633"

[colors.bright]
black = "#998e67"
red = "#7d364e"
green = "#367d4e"
yellow = "#996f33"
blue = "#2d4386"
magenta = "#7d366b"
cyan = "#2d8684"
white = "#1a2633"

[colors.dim]
black = "#998e67"
red = "#7d364e"
green = "#367d4e"
yellow = "#996f33"
blue = "#2d4386"
magenta = "#7d366b"
cyan = "#2d8684"
white = "#1a2633"