[colors.primary]
background = "#dedeed"
foreground = "#221934"
dim_foreground = "#4f3a78"
bright_foreground = "#221934"

[colors.cursor]
text = "#dedeed"
cursor = "#221934"

[colors.vi_mode_cursor]
text = "#dedeed"
cursor = "#221934"

[colors.search.matches]
foreground = "#dedeed"
background = "#9c9cc9"

[colors.search.focused_match]
foreground = "#dedeed"
background = "#669933"

[colors.footer_bar]
foreground = "#dedeed"
background = "#9c9cc9"

[colors.hints.start]
foreground = "#dedeed"
background = "#2966a3"

[colors.hints.end]
foreground = "#dedeed"
background = "#9c9cc9"

[colors.selection]
text = "#dedeed"
background = "#adadd2"

[colors.normal]
black = "#bdbddb"
red = "#a32929"
green = "#669933"
yellow = "#2966a3"
blue = "#da950b"
magenta = "#339999"
cyan = "#993399"
white = "#221934"

[colors.bright]
black = "#bdbddb"
red = "#a32929"
green = "#669933"
yellow = "#2966a3"
blue = "#da950b"
magenta = "#339999"
cyan = "#993399"
white = "#221934"

[colors.dim]
black = "#bdbddb"
red = "#a32929"
green = "#669933"
yellow = "#2966a3"
blue = "#da950b"
magenta = "#339999"
cyan = "#993399"
white = "#221934"