[colors.primary]
background = "#2F3941"
foreground = "#C2E0E0"
dim_foreground = "#AFC1C1"
bright_foreground = "#C2E0E0"

[colors.cursor]
text = "#2F3941"
cursor = "#C2E0E0"

[colors.vi_mode_cursor]
text = "#2F3941"
cursor = "#C2E0E0"

[colors.search.matches]
foreground = "#2F3941"
background = "#759292"

[colors.search.focused_match]
foreground = "#2F3941"
background = "#B7C981"

[colors.footer_bar]
foreground = "#2F3941"
background = "#759292"

[colors.hints.start]
foreground = "#2F3941"
background = "#D7995C"

[colors.hints.end]
foreground = "#2F3941"
background = "#759292"

[colors.selection]
text = "#2F3941"
background = "#5F7878"

[colors.normal]
black = "#465460"
red = "#CA8192"
green = "#B7C981"
yellow = "#D7995C"
blue = "#8382CA"
magenta = "#CB86C5"
cyan = "#81C9B1"
white = "#C2E0E0"

[colors.bright]
black = "#465460"
red = "#CA8192"
green = "#B7C981"
yellow = "#D7995C"
blue = "#8382CA"
magenta = "#CB86C5"
cyan = "#81C9B1"
white = "#C2E0E0"

[colors.dim]
black = "#465460"
red = "#CA8192"
green = "#B7C981"
yellow = "#D7995C"
blue = "#8382CA"
magenta = "#CB86C5"
cyan = "#81C9B1"
white = "#C2E0E0"