[colors.primary]
background = "#2F3941"
foreground = "#cad8d8"
dim_foreground = "#b2bdbd"
bright_foreground = "#cad8d8"

[colors.cursor]
text = "#2F3941"
cursor = "#cad8d8"

[colors.vi_mode_cursor]
text = "#2F3941"
cursor = "#cad8d8"

[colors.search.matches]
foreground = "#2F3941"
background = "#7b8e8e"

[colors.search.focused_match]
foreground = "#2F3941"
background = "#B7C981"

[colors.footer_bar]
foreground = "#2F3941"
background = "#7b8e8e"

[colors.hints.start]
foreground = "#2F3941"
background = "#c9a682"

[colors.hints.end]
foreground = "#2F3941"
background = "#7b8e8e"

[colors.selection]
text = "#2F3941"
background = "#637474"

[colors.normal]
black = "#465460"
red = "#CA8192"
green = "#B7C981"
yellow = "#c9a682"
blue = "#8382CA"
magenta = "#CB86C5"
cyan = "#81C9B1"
white = "#cad8d8"

[colors.bright]
black = "#465460"
red = "#CA8192"
green = "#B7C981"
yellow = "#c9a682"
blue = "#8382CA"
magenta = "#CB86C5"
cyan = "#81C9B1"
white = "#cad8d8"

[colors.dim]
black = "#465460"
red = "#CA8192"
green = "#B7C981"
yellow = "#c9a682"
blue = "#8382CA"
magenta = "#CB86C5"
cyan = "#81C9B1"
white = "#cad8d8"