[colors.primary]
background = "#29212c"
foreground = "#e8c9e8"
dim_foreground = "#c982c9"
bright_foreground = "#e8c9e8"

[colors.cursor]
text = "#29212c"
cursor = "#e8c9e8"

[colors.vi_mode_cursor]
text = "#29212c"
cursor = "#e8c9e8"

[colors.search.matches]
foreground = "#29212c"
background = "#955095"

[colors.search.focused_match]
foreground = "#29212c"
background = "#b366ff"

[colors.footer_bar]
foreground = "#29212c"
background = "#955095"

[colors.hints.start]
foreground = "#29212c"
background = "#f471f4"

[colors.hints.end]
foreground = "#29212c"
background = "#955095"

[colors.selection]
text = "#29212c"
background = "#743e74"

[colors.normal]
black = "#5f4d66"
red = "#ec79b3"
green = "#b366ff"
yellow = "#f471f4"
blue = "#b371f4"
magenta = "#8c66ff"
cyan = "#7979ec"
white = "#e8c9e8"

[colors.bright]
black = "#5f4d66"
red = "#ec79b3"
green = "#b366ff"
yellow = "#f471f4"
blue = "#b371f4"
magenta = "#8c66ff"
cyan = "#7979ec"
white = "#e8c9e8"

[colors.dim]
black = "#5f4d66"
red = "#ec79b3"
green = "#b366ff"
yellow = "#f471f4"
blue = "#b371f4"
magenta = "#8c66ff"
cyan = "#7979ec"
white = "#e8c9e8"