[colors.primary]
background = "#37343d"
foreground = "#d8cace"
dim_foreground = "#bdb2b5"
bright_foreground = "#d8cace"

[colors.cursor]
text = "#37343d"
cursor = "#d8cace"

[colors.vi_mode_cursor]
text = "#37343d"
cursor = "#d8cace"

[colors.search.matches]
foreground = "#37343d"
background = "#7b7b8e"

[colors.search.focused_match]
foreground = "#37343d"
background = "#b5c587"

[colors.footer_bar]
foreground = "#37343d"
background = "#7b7b8e"

[colors.hints.start]
foreground = "#37343d"
background = "#c9a582"

[colors.hints.end]
foreground = "#37343d"
background = "#7b7b8e"

[colors.selection]
text = "#37343d"
background = "#636373"

[colors.normal]
black = "#504c59"
red = "#c5879c"
green = "#b5c587"
yellow = "#c9a582"
blue = "#8b99c1"
magenta = "#c18bb8"
cyan = "#9fc6c6"
white = "#d8cace"

[colors.bright]
black = "#504c59"
red = "#c5879c"
green = "#b5c587"
yellow = "#c9a582"
blue = "#8b99c1"
magenta = "#c18bb8"
cyan = "#9fc6c6"
white = "#d8cace"

[colors.dim]
black = "#504c59"
red = "#c5879c"
green = "#b5c587"
yellow = "#c9a582"
blue = "#8b99c1"
magenta = "#c18bb8"
cyan = "#9fc6c6"
white = "#d8cace"