[colors.primary]
background = "#181d18"
foreground = "#dbbdc4"
dim_foreground = "#b77a89"
bright_foreground = "#dbbdc4"

[colors.cursor]
text = "#181d18"
cursor = "#dbbdc4"

[colors.vi_mode_cursor]
text = "#181d18"
cursor = "#dbbdc4"

[colors.search.matches]
foreground = "#181d18"
background = "#844857"

[colors.search.focused_match]
foreground = "#181d18"
background = "#40be75"

[colors.footer_bar]
foreground = "#181d18"
background = "#844857"

[colors.hints.start]
foreground = "#181d18"
background = "#bebe40"

[colors.hints.end]
foreground = "#181d18"
background = "#844857"

[colors.selection]
text = "#181d18"
background = "#633641"

[colors.normal]
black = "#2F372F"
red = "#be405d"
green = "#40be75"
yellow = "#bebe40"
blue = "#404abe"
magenta = "#9f40be"
cyan = "#40b4be"
white = "#dbbdc4"

[colors.bright]
black = "#2F372F"
red = "#be405d"
green = "#40be75"
yellow = "#bebe40"
blue = "#404abe"
magenta = "#9f40be"
cyan = "#40b4be"
white = "#dbbdc4"

[colors.dim]
black = "#2F372F"
red = "#be405d"
green = "#40be75"
yellow = "#bebe40"
blue = "#404abe"
magenta = "#9f40be"
cyan = "#40b4be"
white = "#dbbdc4"