[colors.primary]
background = "#1b1818"
foreground = "#C1E0B7"
dim_foreground = "#80A375"
bright_foreground = "#C1E0B7"

[colors.cursor]
text = "#1b1818"
cursor = "#C1E0B7"

[colors.vi_mode_cursor]
text = "#1b1818"
cursor = "#C1E0B7"

[colors.search.matches]
foreground = "#1b1818"
background = "#5B7A51"

[colors.search.focused_match]
foreground = "#1b1818"
background = "#b5c587"

[colors.footer_bar]
foreground = "#1b1818"
background = "#5B7A51"

[colors.hints.start]
foreground = "#1b1818"
background = "#DBD270"

[colors.hints.end]
foreground = "#1b1818"
background = "#5B7A51"

[colors.selection]
text = "#1b1818"
background = "#4F6B46"

[colors.normal]
black = "#363030"
red = "#c5879c"
green = "#b5c587"
yellow = "#DBD270"
blue = "#8b99c1"
magenta = "#c18bb8"
cyan = "#93D1D1"
white = "#C1E0B7"

[colors.bright]
black = "#363030"
red = "#c5879c"
green = "#b5c587"
yellow = "#DBD270"
blue = "#8b99c1"
magenta = "#c18bb8"
cyan = "#93D1D1"
white = "#C1E0B7"

[colors.dim]
black = "#363030"
red = "#c5879c"
green = "#b5c587"
yellow = "#DBD270"
blue = "#8b99c1"
magenta = "#c18bb8"
cyan = "#93D1D1"
white = "#C1E0B7"