[colors.primary]
background = "#1E1614"
foreground = "#F0BE77"
dim_foreground = "#D08745"
bright_foreground = "#F0BE77"

[colors.cursor]
text = "#1E1614"
cursor = "#F0BE77"

[colors.vi_mode_cursor]
text = "#1E1614"
cursor = "#F0BE77"

[colors.search.matches]
foreground = "#1E1614"
background = "#854337"

[colors.search.focused_match]
foreground = "#1E1614"
background = "#AAC486"

[colors.footer_bar]
foreground = "#1E1614"
background = "#854337"

[colors.hints.start]
foreground = "#1E1614"
background = "#DBB956"

[colors.hints.end]
foreground = "#1E1614"
background = "#854337"

[colors.selection]
text = "#1E1614"
background = "#6C372C"

[colors.normal]
black = "#3D2C28"
red = "#CC6B65"
green = "#AAC486"
yellow = "#DBB956"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#F0BE77"

[colors.bright]
black = "#3D2C28"
red = "#CC6B65"
green = "#AAC486"
yellow = "#DBB956"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#F0BE77"

[colors.dim]
black = "#3D2C28"
red = "#CC6B65"
green = "#AAC486"
yellow = "#DBB956"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#F0BE77"