[colors.primary]
background = "#292321"
foreground = "#C6EA94"
dim_foreground = "#A3AF6B"
bright_foreground = "#C6EA94"

[colors.cursor]
text = "#292321"
cursor = "#C6EA94"

[colors.vi_mode_cursor]
text = "#292321"
cursor = "#C6EA94"

[colors.search.matches]
foreground = "#292321"
background = "#5B8A7A"

[colors.search.focused_match]
foreground = "#292321"
background = "#AAC486"

[colors.footer_bar]
foreground = "#292321"
background = "#5B8A7A"

[colors.hints.start]
foreground = "#292321"
background = "#E7CC7C"

[colors.hints.end]
foreground = "#292321"
background = "#5B8A7A"

[colors.selection]
text = "#292321"
background = "#527B6D"

[colors.normal]
black = "#463B39"
red = "#CC6B65"
green = "#AAC486"
yellow = "#E7CC7C"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#C6EA94"

[colors.bright]
black = "#463B39"
red = "#CC6B65"
green = "#AAC486"
yellow = "#E7CC7C"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#C6EA94"

[colors.dim]
black = "#463B39"
red = "#CC6B65"
green = "#AAC486"
yellow = "#E7CC7C"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#C6EA94"