[colors.primary]
background = "#2D211E"
foreground = "#F0BE77"
dim_foreground = "#D08745"
bright_foreground = "#F0BE77"

[colors.cursor]
text = "#2D211E"
cursor = "#F0BE77"

[colors.vi_mode_cursor]
text = "#2D211E"
cursor = "#F0BE77"

[colors.search.matches]
foreground = "#2D211E"
background = "#8D493C"

[colors.search.focused_match]
foreground = "#2D211E"
background = "#AAC486"

[colors.footer_bar]
foreground = "#2D211E"
background = "#8D493C"

[colors.hints.start]
foreground = "#2D211E"
background = "#E7CC7C"

[colors.hints.end]
foreground = "#2D211E"
background = "#8D493C"

[colors.selection]
text = "#2D211E"
background = "#6A362C"

[colors.normal]
black = "#4C3833"
red = "#CC6B65"
green = "#AAC486"
yellow = "#E7CC7C"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#F0BE77"

[colors.bright]
black = "#4C3833"
red = "#CC6B65"
green = "#AAC486"
yellow = "#E7CC7C"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#F0BE77"

[colors.dim]
black = "#4C3833"
red = "#CC6B65"
green = "#AAC486"
yellow = "#E7CC7C"
blue = "#60A8D1"
magenta = "#987AB7"
cyan = "#86C4AB"
white = "#F0BE77"