[colors.primary]
background = "#020E1E"
foreground = "#B7EFFA"
dim_foreground = "#59DAF4"
bright_foreground = "#B7EFFA"

[colors.cursor]
text = "#020E1E"
cursor = "#B7EFFA"

[colors.vi_mode_cursor]
text = "#020E1E"
cursor = "#B7EFFA"

[colors.search.matches]
foreground = "#020E1E"
background = "#0E9BA3"

[colors.search.focused_match]
foreground = "#020E1E"
background = "#96C552"

[colors.footer_bar]
foreground = "#020E1E"
background = "#0E9BA3"

[colors.hints.start]
foreground = "#020E1E"
background = "#E48269"

[colors.hints.end]
foreground = "#020E1E"
background = "#0E9BA3"

[colors.selection]
text = "#020E1E"
background = "#057C89"

[colors.normal]
black = "#122949"
red = "#C44D69"
green = "#96C552"
yellow = "#E48269"
blue = "#5282C5"
magenta = "#B94DCB"
cyan = "#52C58C"
white = "#B7EFFA"

[colors.bright]
black = "#122949"
red = "#C44D69"
green = "#96C552"
yellow = "#E48269"
blue = "#5282C5"
magenta = "#B94DCB"
cyan = "#52C58C"
white = "#B7EFFA"

[colors.dim]
black = "#122949"
red = "#C44D69"
green = "#96C552"
yellow = "#E48269"
blue = "#5282C5"
magenta = "#B94DCB"
cyan = "#52C58C"
white = "#B7EFFA"