[colors.primary]
background = "#292723"
foreground = "#BECCCC"
dim_foreground = "#8A9B9B"
bright_foreground = "#BECCCC"

[colors.cursor]
text = "#292723"
cursor = "#BECCCC"

[colors.vi_mode_cursor]
text = "#292723"
cursor = "#BECCCC"

[colors.search.matches]
foreground = "#292723"
background = "#867759"

[colors.search.focused_match]
foreground = "#292723"
background = "#77A86D"

[colors.footer_bar]
foreground = "#292723"
background = "#867759"

[colors.hints.start]
foreground = "#292723"
background = "#D8C075"

[colors.hints.end]
foreground = "#292723"
background = "#867759"

[colors.selection]
text = "#292723"
background = "#72654C"

[colors.normal]
black = "#44413A"
red = "#AE6874"
green = "#77A86D"
yellow = "#D8C075"
blue = "#6E90A8"
magenta = "#A86D9D"
cyan = "#6EA890"
white = "#BECCCC"

[colors.bright]
black = "#44413A"
red = "#AE6874"
green = "#77A86D"
yellow = "#D8C075"
blue = "#6E90A8"
magenta = "#A86D9D"
cyan = "#6EA890"
white = "#BECCCC"

[colors.dim]
black = "#44413A"
red = "#AE6874"
green = "#77A86D"
yellow = "#D8C075"
blue = "#6E90A8"
magenta = "#A86D9D"
cyan = "#6EA890"
white = "#BECCCC"