[colors.primary]
background = "#232729"
foreground = "#C2EFCE"
dim_foreground = "#81C992"
bright_foreground = "#C2EFCE"

[colors.cursor]
text = "#232729"
cursor = "#C2EFCE"

[colors.vi_mode_cursor]
text = "#232729"
cursor = "#C2EFCE"

[colors.search.matches]
foreground = "#232729"
background = "#519762"

[colors.search.focused_match]
foreground = "#232729"
background = "#87D278"

[colors.footer_bar]
foreground = "#232729"
background = "#519762"

[colors.hints.start]
foreground = "#232729"
background = "#EFD074"

[colors.hints.end]
foreground = "#232729"
background = "#519762"

[colors.selection]
text = "#232729"
background = "#3F754C"

[colors.normal]
black = "#3A4144"
red = "#DB6F77"
green = "#87D278"
yellow = "#EFD074"
blue = "#6F93DB"
magenta = "#CA78D2"
cyan = "#78D2C3"
white = "#C2EFCE"

[colors.bright]
black = "#3A4144"
red = "#DB6F77"
green = "#87D278"
yellow = "#EFD074"
blue = "#6F93DB"
magenta = "#CA78D2"
cyan = "#78D2C3"
white = "#C2EFCE"

[colors.dim]
black = "#3A4144"
red = "#DB6F77"
green = "#87D278"
yellow = "#EFD074"
blue = "#6F93DB"
magenta = "#CA78D2"
cyan = "#78D2C3"
white = "#C2EFCE"