[colors.primary]
background = "#2B2C25"
foreground = "#D6D0C1"
dim_foreground = "#AEA283"
bright_foreground = "#D6D0C1"

[colors.cursor]
text = "#2B2C25"
cursor = "#D6D0C1"

[colors.vi_mode_cursor]
text = "#2B2C25"
cursor = "#D6D0C1"

[colors.search.matches]
foreground = "#2B2C25"
background = "#8A7450"

[colors.search.focused_match]
foreground = "#2B2C25"
background = "#B3C08A"

[colors.footer_bar]
foreground = "#2B2C25"
background = "#8A7450"

[colors.hints.start]
foreground = "#2B2C25"
background = "#D7BE74"

[colors.hints.end]
foreground = "#2B2C25"
background = "#8A7450"

[colors.selection]
text = "#2B2C25"
background = "#736144"

[colors.normal]
black = "#46483C"
red = "#C48696"
green = "#B3C08A"
yellow = "#D7BE74"
blue = "#8F8AC0"
magenta = "#B48AC0"
cyan = "#8AC0B2"
white = "#D6D0C1"

[colors.bright]
black = "#46483C"
red = "#C48696"
green = "#B3C08A"
yellow = "#D7BE74"
blue = "#8F8AC0"
magenta = "#B48AC0"
cyan = "#8AC0B2"
white = "#D6D0C1"

[colors.dim]
black = "#46483C"
red = "#C48696"
green = "#B3C08A"
yellow = "#D7BE74"
blue = "#8F8AC0"
magenta = "#B48AC0"
cyan = "#8AC0B2"
white = "#D6D0C1"