[colors.primary]
background = "#2b2f29"
foreground = "#efeddc"
dim_foreground = "#bfbc95"
bright_foreground = "#efeddc"

[colors.cursor]
text = "#2b2f29"
cursor = "#efeddc"

[colors.vi_mode_cursor]
text = "#2b2f29"
cursor = "#efeddc"

[colors.search.matches]
foreground = "#2b2f29"
background = "#687162"

[colors.search.focused_match]
foreground = "#2b2f29"
background = "#a2b77a"

[colors.footer_bar]
foreground = "#2b2f29"
background = "#687162"

[colors.hints.start]
foreground = "#2b2f29"
background = "#c0a659"

[colors.hints.end]
foreground = "#2b2f29"
background = "#687162"

[colors.selection]
text = "#2b2f29"
background = "#575f52"

[colors.normal]
black = "#454b41"
red = "#c17b71"
green = "#a2b77a"
yellow = "#c0a659"
blue = "#8d7bb8"
magenta = "#b27bb8"
cyan = "#5fbab5"
white = "#efeddc"

[colors.bright]
black = "#454b41"
red = "#c17b71"
green = "#a2b77a"
yellow = "#c0a659"
blue = "#8d7bb8"
magenta = "#b27bb8"
cyan = "#5fbab5"
white = "#efeddc"

[colors.dim]
black = "#454b41"
red = "#c17b71"
green = "#a2b77a"
yellow = "#c0a659"
blue = "#8d7bb8"
magenta = "#b27bb8"
cyan = "#5fbab5"
white = "#efeddc"