[colors.primary]
background = "#211712"
foreground = "#e0cd85"
dim_foreground = "#c2b070"
bright_foreground = "#e0cd85"

[colors.cursor]
text = "#211712"
cursor = "#e0cd85"

[colors.vi_mode_cursor]
text = "#211712"
cursor = "#e0cd85"

[colors.search.matches]
foreground = "#211712"
background = "#847748"

[colors.search.focused_match]
foreground = "#211712"
background = "#c9a782"

[colors.footer_bar]
foreground = "#211712"
background = "#847748"

[colors.hints.start]
foreground = "#211712"
background = "#b89494"

[colors.hints.end]
foreground = "#211712"
background = "#847748"

[colors.selection]
text = "#211712"
background = "#635936"

[colors.normal]
black = "#31231b"
red = "#ecec79"
green = "#c9a782"
yellow = "#f4b371"
blue = "#f4d371"
magenta = "#b89494"
cyan = "#b8af94"
white = "#e0cd85"

[colors.bright]
black = "#422e24"
red = "#f2f2a6"
green = "#d9c0a6"
yellow = "#f8cca0"
blue = "#f8e2a0"
magenta = "#ccb3b3"
cyan = "#ccc6b3"
white = "#c2b070"

[colors.dim]
black = "#422e24"
red = "#f2f2a6"
green = "#d9c0a6"
yellow = "#f8cca0"
blue = "#f8e2a0"
magenta = "#ccb3b3"
cyan = "#ccc6b3"
white = "#c2b070"