[colors.primary]
background = "#201d30"
foreground = "#e9c8da"
dim_foreground = "#cc7faa"
bright_foreground = "#e9c8da"

[colors.cursor]
text = "#201d30"
cursor = "#e9c8da"

[colors.vi_mode_cursor]
text = "#201d30"
cursor = "#e9c8da"

[colors.search.matches]
foreground = "#201d30"
background = "#955076"

[colors.search.focused_match]
foreground = "#201d30"
background = "#b375f0"

[colors.footer_bar]
foreground = "#201d30"
background = "#955076"

[colors.hints.start]
foreground = "#201d30"
background = "#f075b3"

[colors.hints.end]
foreground = "#201d30"
background = "#955076"

[colors.selection]
text = "#201d30"
background = "#743e5c"

[colors.normal]
black = "#2a2640"
red = "#f075d1"
green = "#b375f0"
yellow = "#9475f0"
blue = "#7594f0"
magenta = "#f075b3"
cyan = "#d175f0"
white = "#e9c8da"

[colors.bright]
black = "#353050"
red = "#f5a3e0"
green = "#cca3f5"
yellow = "#b8a3f5"
blue = "#a3b8f5"
magenta = "#f5a3cc"
cyan = "#e0a3f5"
white = "#cc7faa"

[colors.dim]
black = "#353050"
red = "#f5a3e0"
green = "#cca3f5"
yellow = "#b8a3f5"
blue = "#a3b8f5"
magenta = "#f5a3cc"
cyan = "#e0a3f5"
white = "#cc7faa"