[colors.primary]
background = "#cacfe7"
foreground = "#371628"
dim_foreground = "#80335d"
bright_foreground = "#371628"

[colors.cursor]
text = "#cacfe7"
cursor = "#371628"

[colors.vi_mode_cursor]
text = "#cacfe7"
cursor = "#371628"

[colors.search.matches]
foreground = "#cacfe7"
background = "#af6a90"

[colors.search.focused_match]
foreground = "#cacfe7"
background = "#591b98"

[colors.footer_bar]
foreground = "#cacfe7"
background = "#af6a90"

[colors.hints.start]
foreground = "#cacfe7"
background = "#8e2559"

[colors.hints.end]
foreground = "#cacfe7"
background = "#af6a90"

[colors.selection]
text = "#cacfe7"
background = "#c18ba8"

[colors.normal]
black = "#b9bfdf"
red = "#8e2574"
green = "#591b98"
yellow = "#8f243e"
blue = "#24598f"
magenta = "#8e2559"
cyan = "#74258e"
white = "#371628"

[colors.bright]
black = "#a7afd7"
red = "#b62f95"
green = "#7322c3"
yellow = "#b82e50"
blue = "#2e73b8"
magenta = "#b62f73"
cyan = "#952fb6"
white = "#80335d"

[colors.dim]
black = "#a7afd7"
red = "#b62f95"
green = "#7322c3"
yellow = "#b82e50"
blue = "#2e73b8"
magenta = "#b62f73"
cyan = "#952fb6"
white = "#80335d"