[colors.primary]
background = "#e4cde2"
foreground = "#230f3d"
dim_foreground = "#54367d"
bright_foreground = "#230f3d"

[colors.cursor]
text = "#e4cde2"
cursor = "#230f3d"

[colors.vi_mode_cursor]
text = "#e4cde2"
cursor = "#230f3d"

[colors.search.matches]
foreground = "#e4cde2"
background = "#75a398"

[colors.search.focused_match]
foreground = "#e4cde2"
background = "#1f7a4d"

[colors.footer_bar]
foreground = "#e4cde2"
background = "#75a398"

[colors.hints.start]
foreground = "#e4cde2"
background = "#1f5993"

[colors.hints.end]
foreground = "#e4cde2"
background = "#75a398"

[colors.selection]
text = "#e4cde2"
background = "#94b8af"

[colors.normal]
black = "#dbbdd9"
red = "#7e7e1b"
green = "#1f7a4d"
yellow = "#8a6b0f"
blue = "#93591f"
magenta = "#1f5993"
cyan = "#1b7e7e"
white = "#230f3d"

[colors.bright]
black = "#d2accf"
red = "#a8a824"
green = "#2aa266"
yellow = "#b88f14"
blue = "#bd7328"
magenta = "#2873bd"
cyan = "#24a8a8"
white = "#54367d"

[colors.dim]
black = "#d2accf"
red = "#a8a824"
green = "#2aa266"
yellow = "#b88f14"
blue = "#bd7328"
magenta = "#2873bd"
cyan = "#24a8a8"
white = "#54367d"