[colors.primary]
background = "#cdcde4"
foreground = "#0f1e3d"
dim_foreground = "#364b7d"
bright_foreground = "#0f1e3d"

[colors.cursor]
text = "#cdcde4"
cursor = "#0f1e3d"

[colors.vi_mode_cursor]
text = "#cdcde4"
cursor = "#0f1e3d"

[colors.search.matches]
foreground = "#cdcde4"
background = "#6a7caf"

[colors.search.focused_match]
foreground = "#cdcde4"
background = "#2d4386"

[colors.footer_bar]
foreground = "#cdcde4"
background = "#6a7caf"

[colors.hints.start]
foreground = "#cdcde4"
background = "#3e248f"

[colors.hints.end]
foreground = "#cdcde4"
background = "#6a7caf"

[colors.selection]
text = "#cdcde4"
background = "#8b99c1"

[colors.normal]
black = "#bdbddb"
red = "#862d86"
green = "#2d4386"
yellow = "#862d2d"
blue = "#8e2559"
magenta = "#3e248f"
cyan = "#24748f"
white = "#0f1e3d"

[colors.bright]
black = "#acacd2"
red = "#ac39ac"
green = "#3956ac"
yellow = "#ac3939"
blue = "#b62f73"
magenta = "#502eb8"
cyan = "#2e95b8"
white = "#364b7d"

[colors.dim]
black = "#acacd2"
red = "#ac39ac"
green = "#3956ac"
yellow = "#ac3939"
blue = "#b62f73"
magenta = "#502eb8"
cyan = "#2e95b8"
white = "#364b7d"