[colors.primary]
background = "#1b1b32"
foreground = "#c2cdf0"
dim_foreground = "#8295c9"
bright_foreground = "#c2cdf0"

[colors.cursor]
text = "#1b1b32"
cursor = "#c2cdf0"

[colors.vi_mode_cursor]
text = "#1b1b32"
cursor = "#c2cdf0"

[colors.search.matches]
foreground = "#1b1b32"
background = "#506395"

[colors.search.focused_match]
foreground = "#1b1b32"
background = "#7d98e8"

[colors.footer_bar]
foreground = "#1b1b32"
background = "#506395"

[colors.hints.start]
foreground = "#1b1b32"
background = "#987de8"

[colors.hints.end]
foreground = "#1b1b32"
background = "#506395"

[colors.selection]
text = "#1b1b32"
background = "#3e4c74"

[colors.normal]
black = "#242442"
red = "#e87de8"
green = "#7d98e8"
yellow = "#e08585"
blue = "#e085b3"
magenta = "#987de8"
cyan = "#7dcde8"
white = "#c2cdf0"

[colors.bright]
black = "#2d2d53"
red = "#f0a8f0"
green = "#a8baf0"
yellow = "#eaaeae"
blue = "#eaaecc"
magenta = "#baa8f0"
cyan = "#a8def0"
white = "#8295c9"

[colors.dim]
black = "#2d2d53"
red = "#f0a8f0"
green = "#a8baf0"
yellow = "#eaaeae"
blue = "#eaaecc"
magenta = "#baa8f0"
cyan = "#a8def0"
white = "#8295c9"