[colors.primary]
background = "#d9d9d9"
foreground = "#3d0f1e"
dim_foreground = "#7d364c"
bright_foreground = "#3d0f1e"

[colors.cursor]
text = "#d9d9d9"
cursor = "#3d0f1e"

[colors.vi_mode_cursor]
text = "#d9d9d9"
cursor = "#3d0f1e"

[colors.search.matches]
foreground = "#d9d9d9"
background = "#af6a80"

[colors.search.focused_match]
foreground = "#d9d9d9"
background = "#981b59"

[colors.footer_bar]
foreground = "#d9d9d9"
background = "#af6a80"

[colors.hints.start]
foreground = "#d9d9d9"
background = "#862d2d"

[colors.hints.end]
foreground = "#d9d9d9"
background = "#af6a80"

[colors.selection]
text = "#d9d9d9"
background = "#c18b9c"

[colors.normal]
black = "#cccccc"
red = "#2d2d86"
green = "#981b59"
yellow = "#592d86"
blue = "#862d86"
magenta = "#862d2d"
cyan = "#983a1b"
white = "#3d0f1e"

[colors.bright]
black = "#bfbfbf"
red = "#3939ac"
green = "#c32273"
yellow = "#7339ac"
blue = "#ac39ac"
magenta = "#ac3939"
cyan = "#c34b22"
white = "#7d364c"

[colors.dim]
black = "#bfbfbf"
red = "#3939ac"
green = "#c32273"
yellow = "#7339ac"
blue = "#ac39ac"
magenta = "#ac3939"
cyan = "#c34b22"
white = "#7d364c"