[colors.primary]
background = "#f6dabc"
foreground = "#3d1e0f"
dim_foreground = "#7d4b36"
bright_foreground = "#3d1e0f"

[colors.cursor]
text = "#f6dabc"
cursor = "#3d1e0f"

[colors.vi_mode_cursor]
text = "#f6dabc"
cursor = "#3d1e0f"

[colors.search.matches]
foreground = "#f6dabc"
background = "#af7c6a"

[colors.search.focused_match]
foreground = "#f6dabc"
background = "#a15c12"

[colors.footer_bar]
foreground = "#f6dabc"
background = "#af7c6a"

[colors.hints.start]
foreground = "#f6dabc"
background = "#9c7b16"

[colors.hints.end]
foreground = "#f6dabc"
background = "#af7c6a"

[colors.selection]
text = "#f6dabc"
background = "#c1998b"

[colors.normal]
black = "#f3cda5"
red = "#253f8e"
green = "#a15c12"
yellow = "#258e59"
blue = "#1b7898"
magenta = "#9c7b16"
cyan = "#983a1b"
white = "#3d1e0f"

[colors.bright]
black = "#f0c18f"
red = "#2f51b6"
green = "#cf7617"
yellow = "#2fb673"
blue = "#229bc3"
magenta = "#c99e1d"
cyan = "#c34b22"
white = "#7d4b36"

[colors.dim]
black = "#f0c18f"
red = "#2f51b6"
green = "#cf7617"
yellow = "#2fb673"
blue = "#229bc3"
magenta = "#c99e1d"
cyan = "#c34b22"
white = "#7d4b36"