[colors.primary]
background = "#c8eaea"
foreground = "#150f3d"
dim_foreground = "#41367d"
bright_foreground = "#150f3d"

[colors.cursor]
text = "#c8eaea"
cursor = "#150f3d"

[colors.vi_mode_cursor]
text = "#c8eaea"
cursor = "#150f3d"

[colors.search.matches]
foreground = "#c8eaea"
background = "#756aaf"

[colors.search.focused_match]
foreground = "#c8eaea"
background = "#248f8f"

[colors.footer_bar]
foreground = "#c8eaea"
background = "#756aaf"

[colors.hints.start]
foreground = "#c8eaea"
background = "#24598f"

[colors.hints.end]
foreground = "#c8eaea"
background = "#756aaf"

[colors.selection]
text = "#c8eaea"
background = "#948bc1"

[colors.normal]
black = "#a3dcdc"
red = "#24248f"
green = "#248f8f"
yellow = "#24598f"
blue = "#8f2459"
magenta = "#8f248f"
cyan = "#59248f"
white = "#150f3d"

[colors.bright]
black = "#a3dcdc"
red = "#24248f"
green = "#248f8f"
yellow = "#24598f"
blue = "#8f2459"
magenta = "#8f248f"
cyan = "#59248f"
white = "#150f3d"

[colors.dim]
black = "#a3dcdc"
red = "#24248f"
green = "#248f8f"
yellow = "#24598f"
blue = "#8f2459"
magenta = "#8f248f"
cyan = "#59248f"
white = "#150f3d"