[colors.primary]
background = "#211712"
foreground = "#c8d4c4"
dim_foreground = "#92a88a"
bright_foreground = "#c8d4c4"

[colors.cursor]
text = "#211712"
cursor = "#c8d4c4"

[colors.vi_mode_cursor]
text = "#211712"
cursor = "#c8d4c4"

[colors.search.matches]
foreground = "#211712"
background = "#5f7557"

[colors.search.focused_match]
foreground = "#211712"
background = "#c9a782"

[colors.footer_bar]
foreground = "#211712"
background = "#5f7557"

[colors.hints.start]
foreground = "#211712"
background = "#b8af94"

[colors.hints.end]
foreground = "#211712"
background = "#5f7557"

[colors.selection]
text = "#211712"
background = "#475841"

[colors.normal]
black = "#422e24"
red = "#82c9a6"
green = "#c9a782"
yellow = "#b8af94"
blue = "#b89494"
magenta = "#82c982"
cyan = "#a6c982"
white = "#c8d4c4"

[colors.bright]
black = "#422e24"
red = "#82c9a6"
green = "#c9a782"
yellow = "#b8af94"
blue = "#b89494"
magenta = "#82c982"
cyan = "#a6c982"
white = "#c8d4c4"

[colors.dim]
black = "#422e24"
red = "#82c9a6"
green = "#c9a782"
yellow = "#b8af94"
blue = "#b89494"
magenta = "#82c982"
cyan = "#a6c982"
white = "#c8d4c4"