[colors.primary]
background = "#211712"
foreground = "#e0cd85"
dim_foreground = "#c2b070"
bright_foreground = "#e0cd85"

[colors.cursor]
text = "#211712"
cursor = "#e0cd85"

[colors.vi_mode_cursor]
text = "#211712"
cursor = "#e0cd85"

[colors.search.matches]
foreground = "#211712"
background = "#847748"

[colors.search.focused_match]
foreground = "#211712"
background = "#c9a782"

[colors.footer_bar]
foreground = "#211712"
background = "#847748"

[colors.hints.start]
foreground = "#211712"
background = "#b8af94"

[colors.hints.end]
foreground = "#211712"
background = "#847748"

[colors.selection]
text = "#211712"
background = "#635936"

[colors.normal]
black = "#422e24"
red = "#ecec79"
green = "#c9a782"
yellow = "#b8af94"
blue = "#b89494"
magenta = "#f4d371"
cyan = "#f4b371"
white = "#e0cd85"

[colors.bright]
black = "#422e24"
red = "#ecec79"
green = "#c9a782"
yellow = "#b8af94"
blue = "#b89494"
magenta = "#f4d371"
cyan = "#f4b371"
white = "#e0cd85"

[colors.dim]
black = "#422e24"
red = "#ecec79"
green = "#c9a782"
yellow = "#b8af94"
blue = "#b89494"
magenta = "#f4d371"
cyan = "#f4b371"
white = "#e0cd85"