[colors.primary]
background = "#211712"
foreground = "#c8d4c4"
dim_foreground = "#92a88a"
bright_foreground = "#c8d4c4"

[colors.cursor]
text = "#211712"
cursor = "#c8d4c4"

[colors.vi_mode_cursor]
text = "#211712"
cursor = "#c8d4c4"

[colors.search.matches]
foreground = "#211712"
background = "#5f7557"

[colors.search.focused_match]
foreground = "#211712"
background = "#c9a782"

[colors.footer_bar]
foreground = "#211712"
background = "#5f7557"

[colors.hints.start]
foreground = "#211712"
background = "#b89494"

[colors.hints.end]
foreground = "#211712"
background = "#5f7557"

[colors.selection]
text = "#211712"
background = "#475841"

[colors.normal]
black = "#31231b"
red = "#82c9a6"
green = "#c9a782"
yellow = "#a6c982"
blue = "#82c982"
magenta = "#b89494"
cyan = "#b8af94"
white = "#c8d4c4"

[colors.bright]
black = "#422e24"
red = "#a6d9bf"
green = "#d9c0a6"
yellow = "#bfd9a6"
blue = "#a6d9a6"
magenta = "#ccb3b3"
cyan = "#ccc6b3"
white = "#92a88a"

[colors.dim]
black = "#422e24"
red = "#a6d9bf"
green = "#d9c0a6"
yellow = "#bfd9a6"
blue = "#a6d9a6"
magenta = "#ccb3b3"
cyan = "#ccc6b3"
white = "#92a88a"