[colors.primary]
background = "#f4dbbe"
foreground = "#41170b"
dim_foreground = "#86412d"
bright_foreground = "#41170b"

[colors.cursor]
text = "#f4dbbe"
cursor = "#41170b"

[colors.vi_mode_cursor]
text = "#f4dbbe"
cursor = "#41170b"

[colors.search.matches]
foreground = "#f4dbbe"
background = "#ba745e"

[colors.search.focused_match]
foreground = "#f4dbbe"
background = "#917108"

[colors.footer_bar]
foreground = "#f4dbbe"
background = "#ba745e"

[colors.hints.start]
foreground = "#f4dbbe"
background = "#912a08"

[colors.hints.end]
foreground = "#f4dbbe"
background = "#ba745e"

[colors.selection]
text = "#f4dbbe"
background = "#c99282"

[colors.normal]
black = "#edc292"
red = "#910808"
green = "#917108"
yellow = "#912a08"
blue = "#831631"
magenta = "#681683"
cyan = "#831668"
white = "#41170b"

[colors.bright]
black = "#edc292"
red = "#910808"
green = "#917108"
yellow = "#912a08"
blue = "#831631"
magenta = "#681683"
cyan = "#831668"
white = "#41170b"

[colors.dim]
black = "#edc292"
red = "#910808"
green = "#917108"
yellow = "#912a08"
blue = "#831631"
magenta = "#681683"
cyan = "#831668"
white = "#41170b"