[colors.primary]
background = "#201d30"
foreground = "#e9c8da"
dim_foreground = "#cc7faa"
bright_foreground = "#e9c8da"

[colors.cursor]
text = "#201d30"
cursor = "#e9c8da"

[colors.vi_mode_cursor]
text = "#201d30"
cursor = "#e9c8da"

[colors.search.matches]
foreground = "#201d30"
background = "#955076"

[colors.search.focused_match]
foreground = "#201d30"
background = "#b375f0"

[colors.footer_bar]
foreground = "#201d30"
background = "#955076"

[colors.hints.start]
foreground = "#201d30"
background = "#d175f0"

[colors.hints.end]
foreground = "#201d30"
background = "#955076"

[colors.selection]
text = "#201d30"
background = "#743e5c"

[colors.normal]
black = "#353050"
red = "#f075d1"
green = "#b375f0"
yellow = "#d175f0"
blue = "#f075b3"
magenta = "#7594f0"
cyan = "#9475f0"
white = "#e9c8da"

[colors.bright]
black = "#353050"
red = "#f075d1"
green = "#b375f0"
yellow = "#d175f0"
blue = "#f075b3"
magenta = "#7594f0"
cyan = "#9475f0"
white = "#e9c8da"

[colors.dim]
black = "#353050"
red = "#f075d1"
green = "#b375f0"
yellow = "#d175f0"
blue = "#f075b3"
magenta = "#7594f0"
cyan = "#9475f0"
white = "#e9c8da"