[colors.primary]
background = "#cacfe7"
foreground = "#371628"
dim_foreground = "#80335d"
bright_foreground = "#371628"

[colors.cursor]
text = "#cacfe7"
cursor = "#371628"

[colors.vi_mode_cursor]
text = "#cacfe7"
cursor = "#371628"

[colors.search.matches]
foreground = "#cacfe7"
background = "#af6a90"

[colors.search.focused_match]
foreground = "#cacfe7"
background = "#591b98"

[colors.footer_bar]
foreground = "#cacfe7"
background = "#af6a90"

[colors.hints.start]
foreground = "#cacfe7"
background = "#74258e"

[colors.hints.end]
foreground = "#cacfe7"
background = "#af6a90"

[colors.selection]
text = "#cacfe7"
background = "#c18ba8"

[colors.normal]
black = "#a7afd7"
red = "#8e2574"
green = "#591b98"
yellow = "#74258e"
blue = "#8e2559"
magenta = "#24598f"
cyan = "#8f243e"
white = "#371628"

[colors.bright]
black = "#a7afd7"
red = "#8e2574"
green = "#591b98"
yellow = "#74258e"
blue = "#8e2559"
magenta = "#24598f"
cyan = "#8f243e"
white = "#371628"

[colors.dim]
black = "#a7afd7"
red = "#8e2574"
green = "#591b98"
yellow = "#74258e"
blue = "#8e2559"
magenta = "#24598f"
cyan = "#8f243e"
white = "#371628"