[colors.primary]
background = "#201c30"
foreground = "#f0ddc2"
dim_foreground = "#c9ae82"
bright_foreground = "#f0ddc2"

[colors.cursor]
text = "#201c30"
cursor = "#f0ddc2"

[colors.vi_mode_cursor]
text = "#201c30"
cursor = "#f0ddc2"

[colors.search.matches]
foreground = "#201c30"
background = "#a18a45"

[colors.search.focused_match]
foreground = "#201c30"
background = "#a79fc6"

[colors.footer_bar]
foreground = "#201c30"
background = "#a18a45"

[colors.hints.start]
foreground = "#201c30"
background = "#bd8bda"

[colors.hints.end]
foreground = "#201c30"
background = "#a18a45"

[colors.selection]
text = "#201c30"
background = "#7d6b36"

[colors.normal]
black = "#362f50"
red = "#edd95e"
green = "#a79fc6"
yellow = "#bd8bda"
blue = "#e97ce5"
magenta = "#e8987d"
cyan = "#e9bf7c"
white = "#f0ddc2"

[colors.bright]
black = "#362f50"
red = "#edd95e"
green = "#a79fc6"
yellow = "#bd8bda"
blue = "#e97ce5"
magenta = "#e8987d"
cyan = "#e9bf7c"
white = "#f0ddc2"

[colors.dim]
black = "#362f50"
red = "#edd95e"
green = "#a79fc6"
yellow = "#bd8bda"
blue = "#e97ce5"
magenta = "#e8987d"
cyan = "#e9bf7c"
white = "#f0ddc2"