[colors.primary]
background = "#ddd7d4"
foreground = "#3d0f15"
dim_foreground = "#7d3641"
bright_foreground = "#3d0f15"

[colors.cursor]
text = "#ddd7d4"
cursor = "#3d0f15"

[colors.vi_mode_cursor]
text = "#ddd7d4"
cursor = "#3d0f15"

[colors.search.matches]
foreground = "#ddd7d4"
background = "#af6a74"

[colors.search.focused_match]
foreground = "#ddd7d4"
background = "#914321"

[colors.footer_bar]
foreground = "#ddd7d4"
background = "#af6a74"

[colors.hints.start]
foreground = "#ddd7d4"
background = "#8e2526"

[colors.hints.end]
foreground = "#ddd7d4"
background = "#af6a74"

[colors.selection]
text = "#ddd7d4"
background = "#c18b93"

[colors.normal]
black = "#c7bdb8"
red = "#b32d00"
green = "#914321"
yellow = "#8e2526"
blue = "#653f73"
magenta = "#69494e"
cyan = "#81325e"
white = "#3d0f15"

[colors.bright]
black = "#c7bdb8"
red = "#b32d00"
green = "#914321"
yellow = "#8e2526"
blue = "#653f73"
magenta = "#69494e"
cyan = "#81325e"
white = "#3d0f15"

[colors.dim]
black = "#c7bdb8"
red = "#b32d00"
green = "#914321"
yellow = "#8e2526"
blue = "#653f73"
magenta = "#69494e"
cyan = "#81325e"
white = "#3d0f15"