[colors.primary]
background = "#2b2522"
foreground = "#ecc6cb"
dim_foreground = "#c9828d"
bright_foreground = "#ecc6cb"

[colors.cursor]
text = "#2b2522"
cursor = "#ecc6cb"

[colors.vi_mode_cursor]
text = "#2b2522"
cursor = "#ecc6cb"

[colors.search.matches]
foreground = "#2b2522"
background = "#95505a"

[colors.search.focused_match]
foreground = "#2b2522"
background = "#e39f82"

[colors.footer_bar]
foreground = "#2b2522"
background = "#95505a"

[colors.hints.start]
foreground = "#2b2522"
background = "#e08587"

[colors.hints.end]
foreground = "#2b2522"
background = "#95505a"

[colors.selection]
text = "#2b2522"
background = "#743e45"

[colors.normal]
black = "#473d38"
red = "#ff8c66"
green = "#e39f82"
yellow = "#e08587"
blue = "#bd9cc9"
magenta = "#c0a5a9"
cyan = "#d491b7"
white = "#ecc6cb"

[colors.bright]
black = "#473d38"
red = "#ff8c66"
green = "#e39f82"
yellow = "#e08587"
blue = "#bd9cc9"
magenta = "#c0a5a9"
cyan = "#d491b7"
white = "#ecc6cb"

[colors.dim]
black = "#473d38"
red = "#ff8c66"
green = "#e39f82"
yellow = "#e08587"
blue = "#bd9cc9"
magenta = "#c0a5a9"
cyan = "#d491b7"
white = "#ecc6cb"