[colors.primary]
background = "#ddd5dd"
foreground = "#361f17"
dim_foreground = "#7d4936"
bright_foreground = "#361f17"

[colors.cursor]
text = "#ddd5dd"
cursor = "#361f17"

[colors.vi_mode_cursor]
text = "#ddd5dd"
cursor = "#361f17"

[colors.search.matches]
foreground = "#ddd5dd"
background = "#ba775e"

[colors.search.focused_match]
foreground = "#ddd5dd"
background = "#8f4d0a"

[colors.footer_bar]
foreground = "#ddd5dd"
background = "#ba775e"

[colors.hints.start]
foreground = "#ddd5dd"
background = "#8e6d0b"

[colors.hints.end]
foreground = "#ddd5dd"
background = "#ba775e"

[colors.selection]
text = "#ddd5dd"
background = "#c99582"

[colors.normal]
black = "#c6b8c6"
red = "#181881"
green = "#8f4d0a"
yellow = "#8e6d0b"
blue = "#8e2c0b"
magenta = "#811881"
cyan = "#4d1881"
white = "#361f17"

[colors.bright]
black = "#c6b8c6"
red = "#181881"
green = "#8f4d0a"
yellow = "#8e6d0b"
blue = "#8e2c0b"
magenta = "#811881"
cyan = "#4d1881"
white = "#361f17"

[colors.dim]
black = "#c6b8c6"
red = "#181881"
green = "#8f4d0a"
yellow = "#8e6d0b"
blue = "#8e2c0b"
magenta = "#811881"
cyan = "#4d1881"
white = "#361f17"