[colors.primary]
background = "#1b181b"
foreground = "#f1cca7"
dim_foreground = "#cc9966"
bright_foreground = "#f1cca7"

[colors.cursor]
text = "#1b181b"
cursor = "#f1cca7"

[colors.vi_mode_cursor]
text = "#1b181b"
cursor = "#f1cca7"

[colors.search.matches]
foreground = "#1b181b"
background = "#8f663d"

[colors.search.focused_match]
foreground = "#1b181b"
background = "#f3a658"

[colors.footer_bar]
foreground = "#1b181b"
background = "#8f663d"

[colors.hints.start]
foreground = "#1b181b"
background = "#f2cc5a"

[colors.hints.end]
foreground = "#1b181b"
background = "#8f663d"

[colors.selection]
text = "#1b181b"
background = "#6b4d2e"

[colors.normal]
black = "#363036"
red = "#6969e2"
green = "#f3a658"
yellow = "#f2cc5a"
blue = "#f2805a"
magenta = "#e269e2"
cyan = "#a669e2"
white = "#f1cca7"

[colors.bright]
black = "#363036"
red = "#6969e2"
green = "#f3a658"
yellow = "#f2cc5a"
blue = "#f2805a"
magenta = "#e269e2"
cyan = "#a669e2"
white = "#f1cca7"

[colors.dim]
black = "#363036"
red = "#6969e2"
green = "#f3a658"
yellow = "#f2cc5a"
blue = "#f2805a"
magenta = "#e269e2"
cyan = "#a669e2"
white = "#f1cca7"