[colors.primary]
background = "#262626"
foreground = "#f9e7b8"
dim_foreground = "#dbc170"
bright_foreground = "#f9e7b8"

[colors.cursor]
text = "#262626"
cursor = "#f9e7b8"

[colors.vi_mode_cursor]
text = "#262626"
cursor = "#f9e7b8"

[colors.search.matches]
foreground = "#262626"
background = "#4e977f"

[colors.search.focused_match]
foreground = "#262626"
background = "#f0f075"

[colors.footer_bar]
foreground = "#262626"
background = "#4e977f"

[colors.hints.start]
foreground = "#262626"
background = "#b3f075"

[colors.hints.end]
foreground = "#262626"
background = "#4e977f"

[colors.selection]
text = "#262626"
background = "#3d7663"

[colors.normal]
black = "#404040"
red = "#75b3f0"
green = "#f0f075"
yellow = "#b3f075"
blue = "#75f075"
magenta = "#75f0f0"
cyan = "#75f0b3"
white = "#f9e7b8"

[colors.bright]
black = "#404040"
red = "#75b3f0"
green = "#f0f075"
yellow = "#b3f075"
blue = "#75f075"
magenta = "#75f0f0"
cyan = "#75f0b3"
white = "#f9e7b8"

[colors.dim]
black = "#404040"
red = "#75b3f0"
green = "#f0f075"
yellow = "#b3f075"
blue = "#75f075"
magenta = "#75f0f0"
cyan = "#75f0b3"
white = "#f9e7b8"