[colors.primary]
background = "#f5e6bd"
foreground = "#392713"
dim_foreground = "#865b2d"
bright_foreground = "#392713"

[colors.cursor]
text = "#f5e6bd"
cursor = "#392713"

[colors.vi_mode_cursor]
text = "#f5e6bd"
cursor = "#392713"

[colors.search.matches]
foreground = "#f5e6bd"
background = "#c68e53"

[colors.search.focused_match]
foreground = "#f5e6bd"
background = "#1b647e"

[colors.footer_bar]
foreground = "#f5e6bd"
background = "#c68e53"

[colors.hints.start]
foreground = "#f5e6bd"
background = "#2d4386"

[colors.hints.end]
foreground = "#f5e6bd"
background = "#c68e53"

[colors.selection]
text = "#f5e6bd"
background = "#d2a779"

[colors.normal]
black = "#f2dea6"
red = "#542673"
green = "#1b647e"
yellow = "#26734d"
blue = "#4a446f"
magenta = "#2d4386"
cyan = "#178282"
white = "#392713"

[colors.bright]
black = "#eed590"
red = "#703399"
green = "#2485a8"
yellow = "#339966"
blue = "#5f578e"
magenta = "#3956ac"
cyan = "#1fadad"
white = "#865b2d"

[colors.dim]
black = "#eed590"
red = "#703399"
green = "#2485a8"
yellow = "#339966"
blue = "#5f578e"
magenta = "#3956ac"
cyan = "#1fadad"
white = "#865b2d"