[colors.primary]
background = "#d5d7dd"
foreground = "#1f222d"
dim_foreground = "#495069"
bright_foreground = "#1f222d"

[colors.cursor]
text = "#d5d7dd"
cursor = "#1f222d"

[colors.vi_mode_cursor]
text = "#d5d7dd"
cursor = "#1f222d"

[colors.search.matches]
foreground = "#d5d7dd"
background = "#808699"

[colors.search.focused_match]
foreground = "#d5d7dd"
background = "#8a4d0f"

[colors.footer_bar]
foreground = "#d5d7dd"
background = "#808699"

[colors.hints.start]
foreground = "#d5d7dd"
background = "#8a670f"

[colors.hints.end]
foreground = "#d5d7dd"
background = "#808699"

[colors.selection]
text = "#d5d7dd"
background = "#9ca1b0"

[colors.normal]
black = "#b8bcc6"
red = "#1b647e"
green = "#8a4d0f"
yellow = "#8a670f"
blue = "#917a08"
magenta = "#178282"
cyan = "#263773"
white = "#1f222d"

[colors.bright]
black = "#b8bcc6"
red = "#1b647e"
green = "#8a4d0f"
yellow = "#8a670f"
blue = "#917a08"
magenta = "#178282"
cyan = "#263773"
white = "#1f222d"

[colors.dim]
black = "#b8bcc6"
red = "#1b647e"
green = "#8a4d0f"
yellow = "#8a670f"
blue = "#917a08"
magenta = "#178282"
cyan = "#263773"
white = "#1f222d"