[colors.primary]
background = "#241933"
foreground = "#f0c2ea"
dim_foreground = "#c982be"
bright_foreground = "#f0c2ea"

[colors.cursor]
text = "#241933"
cursor = "#f0c2ea"

[colors.vi_mode_cursor]
text = "#241933"
cursor = "#f0c2ea"

[colors.search.matches]
foreground = "#241933"
background = "#95508a"

[colors.search.focused_match]
foreground = "#241933"
background = "#9475f0"

[colors.footer_bar]
foreground = "#241933"
background = "#95508a"

[colors.hints.start]
foreground = "#241933"
background = "#cd7de8"

[colors.hints.end]
foreground = "#241933"
background = "#95508a"

[colors.selection]
text = "#241933"
background = "#743e6b"

[colors.normal]
black = "#3c2a55"
red = "#b3f075"
green = "#9475f0"
yellow = "#cd7de8"
blue = "#e87dcd"
magenta = "#75f075"
cyan = "#75f0b3"
white = "#f0c2ea"

[colors.bright]
black = "#3c2a55"
red = "#b3f075"
green = "#9475f0"
yellow = "#cd7de8"
blue = "#e87dcd"
magenta = "#75f075"
cyan = "#75f0b3"
white = "#f0c2ea"

[colors.dim]
black = "#3c2a55"
red = "#b3f075"
green = "#9475f0"
yellow = "#cd7de8"
blue = "#e87dcd"
magenta = "#75f075"
cyan = "#75f0b3"
white = "#f0c2ea"