[colors.primary]
background = "#decde4"
foreground = "#240f3d"
dim_foreground = "#54367d"
bright_foreground = "#240f3d"

[colors.cursor]
text = "#decde4"
cursor = "#240f3d"

[colors.vi_mode_cursor]
text = "#decde4"
cursor = "#240f3d"

[colors.search.matches]
foreground = "#decde4"
background = "#8765b3"

[colors.search.focused_match]
foreground = "#decde4"
background = "#260d73"

[colors.footer_bar]
foreground = "#decde4"
background = "#8765b3"

[colors.hints.start]
foreground = "#decde4"
background = "#56136c"

[colors.hints.end]
foreground = "#decde4"
background = "#8765b3"

[colors.selection]
text = "#decde4"
background = "#a187c4"

[colors.normal]
black = "#c8acd2"
red = "#40730d"
green = "#260d73"
yellow = "#56136c"
blue = "#6c1356"
magenta = "#0d730d"
cyan = "#0d7340"
white = "#240f3d"

[colors.bright]
black = "#c8acd2"
red = "#40730d"
green = "#260d73"
yellow = "#56136c"
blue = "#6c1356"
magenta = "#0d730d"
cyan = "#0d7340"
white = "#240f3d"

[colors.dim]
black = "#c8acd2"
red = "#40730d"
green = "#260d73"
yellow = "#56136c"
blue = "#6c1356"
magenta = "#0d730d"
cyan = "#0d7340"
white = "#240f3d"