[colors.primary]
background = "#d9d3de"
foreground = "#0f0f3e"
dim_foreground = "#36367d"
bright_foreground = "#0f0f3e"

[colors.cursor]
text = "#d9d3de"
cursor = "#0f0f3e"

[colors.vi_mode_cursor]
text = "#d9d3de"
cursor = "#0f0f3e"

[colors.search.matches]
foreground = "#d9d3de"
background = "#7b7b9d"

[colors.search.focused_match]
foreground = "#d9d3de"
background = "#990000"

[colors.footer_bar]
foreground = "#d9d3de"
background = "#7b7b9d"

[colors.hints.start]
foreground = "#d9d3de"
background = "#000099"

[colors.hints.end]
foreground = "#d9d3de"
background = "#7b7b9d"

[colors.selection]
text = "#d9d3de"
background = "#9898b3"

[colors.normal]
black = "#c0b6c8"
red = "#005c99"
green = "#990000"
yellow = "#000099"
blue = "#730099"
magenta = "#99004d"
cyan = "#4d0099"
white = "#0f0f3e"

[colors.bright]
black = "#c0b6c8"
red = "#005c99"
green = "#990000"
yellow = "#000099"
blue = "#730099"
magenta = "#99004d"
cyan = "#4d0099"
white = "#0f0f3e"

[colors.dim]
black = "#c0b6c8"
red = "#005c99"
green = "#990000"
yellow = "#000099"
blue = "#730099"
magenta = "#99004d"
cyan = "#4d0099"
white = "#0f0f3e"