[colors.primary]
background = "#1b1b32"
foreground = "#d9d3de"
dim_foreground = "#a798b3"
bright_foreground = "#d9d3de"

[colors.cursor]
text = "#1b1b32"
cursor = "#d9d3de"

[colors.vi_mode_cursor]
text = "#1b1b32"
cursor = "#d9d3de"

[colors.search.matches]
foreground = "#1b1b32"
background = "#736284"

[colors.search.focused_match]
foreground = "#1b1b32"
background = "#ff6666"

[colors.footer_bar]
foreground = "#1b1b32"
background = "#736284"

[colors.hints.start]
foreground = "#1b1b32"
background = "#6666ff"

[colors.hints.end]
foreground = "#1b1b32"
background = "#736284"

[colors.selection]
text = "#1b1b32"
background = "#5a4c67"

[colors.normal]
black = "#2d2d53"
red = "#66c2ff"
green = "#ff6666"
yellow = "#6666ff"
blue = "#d966ff"
magenta = "#ff66b3"
cyan = "#b366ff"
white = "#d9d3de"

[colors.bright]
black = "#2d2d53"
red = "#66c2ff"
green = "#ff6666"
yellow = "#6666ff"
blue = "#d966ff"
magenta = "#ff66b3"
cyan = "#b366ff"
white = "#d9d3de"

[colors.dim]
black = "#2d2d53"
red = "#66c2ff"
green = "#ff6666"
yellow = "#6666ff"
blue = "#d966ff"
magenta = "#ff66b3"
cyan = "#b366ff"
white = "#d9d3de"