[colors.primary]
background = "#25222b"
foreground = "#f4e6bd"
dim_foreground = "#e5c366"
bright_foreground = "#f4e6bd"

[colors.cursor]
text = "#25222b"
cursor = "#f4e6bd"

[colors.vi_mode_cursor]
text = "#25222b"
cursor = "#f4e6bd"

[colors.search.matches]
foreground = "#25222b"
background = "#6e6581"

[colors.search.focused_match]
foreground = "#25222b"
background = "#b376ef"

[colors.footer_bar]
foreground = "#25222b"
background = "#6e6581"

[colors.hints.start]
foreground = "#25222b"
background = "#e085e0"

[colors.hints.end]
foreground = "#25222b"
background = "#6e6581"

[colors.selection]
text = "#25222b"
background = "#564f64"

[colors.normal]
black = "#3d3847"
red = "#7676ef"
green = "#b376ef"
yellow = "#e085e0"
blue = "#e085b3"
magenta = "#76b3ef"
cyan = "#76efef"
white = "#f4e6bd"

[colors.bright]
black = "#3d3847"
red = "#7676ef"
green = "#b376ef"
yellow = "#e085e0"
blue = "#e085b3"
magenta = "#76b3ef"
cyan = "#76efef"
white = "#f4e6bd"

[colors.dim]
black = "#3d3847"
red = "#7676ef"
green = "#b376ef"
yellow = "#e085e0"
blue = "#e085b3"
magenta = "#76b3ef"
cyan = "#76efef"
white = "#f4e6bd"