[colors.primary]
background = "#e4cdd2"
foreground = "#241b32"
dim_foreground = "#57476b"
bright_foreground = "#241b32"

[colors.cursor]
text = "#e4cdd2"
cursor = "#241b32"

[colors.vi_mode_cursor]
text = "#e4cdd2"
cursor = "#241b32"

[colors.search.matches]
foreground = "#e4cdd2"
background = "#8b7b9d"

[colors.search.focused_match]
foreground = "#e4cdd2"
background = "#8c2674"

[colors.footer_bar]
foreground = "#e4cdd2"
background = "#8b7b9d"

[colors.hints.start]
foreground = "#e4cdd2"
background = "#824530"

[colors.hints.end]
foreground = "#e4cdd2"
background = "#8b7b9d"

[colors.selection]
text = "#e4cdd2"
background = "#a498b3"

[colors.normal]
black = "#d2acb4"
red = "#48486a"
green = "#8c2674"
yellow = "#824530"
blue = "#931f3e"
magenta = "#674c56"
cyan = "#57367c"
white = "#241b32"

[colors.bright]
black = "#d2acb4"
red = "#48486a"
green = "#8c2674"
yellow = "#824530"
blue = "#931f3e"
magenta = "#674c56"
cyan = "#57367c"
white = "#241b32"

[colors.dim]
black = "#d2acb4"
red = "#48486a"
green = "#8c2674"
yellow = "#824530"
blue = "#931f3e"
magenta = "#674c56"
cyan = "#57367c"
white = "#241b32"