[colors.primary]
background = "#29222a"
foreground = "#f4dfbe"
dim_foreground = "#d2b279"
bright_foreground = "#f4dfbe"

[colors.cursor]
text = "#29222a"
cursor = "#f4dfbe"

[colors.vi_mode_cursor]
text = "#29222a"
cursor = "#f4dfbe"

[colors.search.matches]
foreground = "#29222a"
background = "#a17f45"

[colors.search.focused_match]
foreground = "#29222a"
background = "#ffc766"

[colors.footer_bar]
foreground = "#29222a"
background = "#a17f45"

[colors.hints.start]
foreground = "#29222a"
background = "#ffe166"

[colors.hints.end]
foreground = "#29222a"
background = "#a17f45"

[colors.selection]
text = "#29222a"
background = "#7d6336"

[colors.normal]
black = "#453947"
red = "#e87db3"
green = "#ffc766"
yellow = "#ffe166"
blue = "#e8867d"
magenta = "#e87de8"
cyan = "#ff6673"
white = "#f4dfbe"

[colors.bright]
black = "#453947"
red = "#e87db3"
green = "#ffc766"
yellow = "#ffe166"
blue = "#e8867d"
magenta = "#e87de8"
cyan = "#ff6673"
white = "#f4dfbe"

[colors.dim]
black = "#453947"
red = "#e87db3"
green = "#ffc766"
yellow = "#ffe166"
blue = "#e8867d"
magenta = "#e87de8"
cyan = "#ff6673"
white = "#f4dfbe"