[colors.primary]
background = "#29222a"
foreground = "#ebadbc"
dim_foreground = "#c27085"
bright_foreground = "#ebadbc"

[colors.cursor]
text = "#29222a"
cursor = "#ebadbc"

[colors.vi_mode_cursor]
text = "#29222a"
cursor = "#ebadbc"

[colors.search.matches]
foreground = "#29222a"
background = "#844857"

[colors.search.focused_match]
foreground = "#29222a"
background = "#ff6673"

[colors.footer_bar]
foreground = "#29222a"
background = "#844857"

[colors.hints.start]
foreground = "#29222a"
background = "#e87de8"

[colors.hints.end]
foreground = "#29222a"
background = "#844857"

[colors.selection]
text = "#29222a"
background = "#633641"

[colors.normal]
black = "#453947"
red = "#ffe166"
green = "#ff6673"
yellow = "#e87de8"
blue = "#e87db3"
magenta = "#e8867d"
cyan = "#ffc766"
white = "#ebadbc"

[colors.bright]
black = "#453947"
red = "#ffe166"
green = "#ff6673"
yellow = "#e87de8"
blue = "#e87db3"
magenta = "#e8867d"
cyan = "#ffc766"
white = "#ebadbc"

[colors.dim]
black = "#453947"
red = "#ffe166"
green = "#ff6673"
yellow = "#e87de8"
blue = "#e87db3"
magenta = "#e8867d"
cyan = "#ffc766"
white = "#ebadbc"