[colors.primary]
background = "#29222a"
foreground = "#f4dfbe"
dim_foreground = "#d2b279"
bright_foreground = "#f4dfbe"

[colors.cursor]
text = "#29222a"
cursor = "#f4dfbe"

[colors.vi_mode_cursor]
text = "#29222a"
cursor = "#f4dfbe"

[colors.search.matches]
foreground = "#29222a"
background = "#a17f45"

[colors.search.focused_match]
foreground = "#29222a"
background = "#ffc766"

[colors.footer_bar]
foreground = "#29222a"
background = "#a17f45"

[colors.hints.start]
foreground = "#29222a"
background = "#e8867d"

[colors.hints.end]
foreground = "#29222a"
background = "#a17f45"

[colors.selection]
text = "#29222a"
background = "#7d6336"

[colors.normal]
black = "#372d39"
red = "#e87db3"
green = "#ffc766"
yellow = "#ff6673"
blue = "#e87de8"
magenta = "#e8867d"
cyan = "#ffe166"
white = "#f4dfbe"

[colors.bright]
black = "#453947"
red = "#f0a8cc"
green = "#ffda99"
yellow = "#ff99a2"
blue = "#f0a8f0"
magenta = "#f0aea8"
cyan = "#ffeb99"
white = "#d2b279"

[colors.dim]
black = "#453947"
red = "#f0a8cc"
green = "#ffda99"
yellow = "#ff99a2"
blue = "#f0a8f0"
magenta = "#f0aea8"
cyan = "#ffeb99"
white = "#d2b279"