[colors.primary]
background = "#f9ebb8"
foreground = "#3d0f2c"
dim_foreground = "#7d3662"
bright_foreground = "#3d0f2c"

[colors.cursor]
text = "#f9ebb8"
cursor = "#3d0f2c"

[colors.vi_mode_cursor]
text = "#f9ebb8"
cursor = "#3d0f2c"

[colors.search.matches]
foreground = "#f9ebb8"
background = "#af6a95"

[colors.search.focused_match]
foreground = "#f9ebb8"
background = "#91082a"

[colors.footer_bar]
foreground = "#f9ebb8"
background = "#af6a95"

[colors.hints.start]
foreground = "#f9ebb8"
background = "#91086f"

[colors.hints.end]
foreground = "#f9ebb8"
background = "#af6a95"

[colors.selection]
text = "#f9ebb8"
background = "#c18bad"

[colors.normal]
black = "#f5de8a"
red = "#922a07"
green = "#91082a"
yellow = "#91086f"
blue = "#6f0891"
magenta = "#914d08"
cyan = "#916f08"
white = "#3d0f2c"

[colors.bright]
black = "#f5de8a"
red = "#922a07"
green = "#91082a"
yellow = "#91086f"
blue = "#6f0891"
magenta = "#914d08"
cyan = "#916f08"
white = "#3d0f2c"

[colors.dim]
black = "#f5de8a"
red = "#922a07"
green = "#91082a"
yellow = "#91086f"
blue = "#6f0891"
magenta = "#914d08"
cyan = "#916f08"
white = "#3d0f2c"