[colors.primary]
background = "#ecc6ec"
foreground = "#1a1a1a"
dim_foreground = "#4d4d4d"
bright_foreground = "#1a1a1a"

[colors.cursor]
text = "#ecc6ec"
cursor = "#1a1a1a"

[colors.vi_mode_cursor]
text = "#ecc6ec"
cursor = "#1a1a1a"

[colors.search.matches]
foreground = "#ecc6ec"
background = "#a375a3"

[colors.search.focused_match]
foreground = "#ecc6ec"
background = "#821782"

[colors.footer_bar]
foreground = "#ecc6ec"
background = "#a375a3"

[colors.hints.start]
foreground = "#ecc6ec"
background = "#82174d"

[colors.hints.end]
foreground = "#ecc6ec"
background = "#a375a3"

[colors.selection]
text = "#ecc6ec"
background = "#b894b8"

[colors.normal]
black = "#df9fdf"
red = "#1f1f7a"
green = "#821782"
yellow = "#82174d"
blue = "#821717"
magenta = "#7a361f"
cyan = "#4d0f8a"
white = "#1a1a1a"

[colors.bright]
black = "#df9fdf"
red = "#1f1f7a"
green = "#821782"
yellow = "#82174d"
blue = "#821717"
magenta = "#7a361f"
cyan = "#4d0f8a"
white = "#1a1a1a"

[colors.dim]
black = "#df9fdf"
red = "#1f1f7a"
green = "#821782"
yellow = "#82174d"
blue = "#821717"
magenta = "#7a361f"
cyan = "#4d0f8a"
white = "#1a1a1a"