[colors.primary]
background = "#1a1a1a"
foreground = "#ebadad"
dim_foreground = "#c27070"
bright_foreground = "#ebadad"

[colors.cursor]
text = "#1a1a1a"
cursor = "#ebadad"

[colors.vi_mode_cursor]
text = "#1a1a1a"
cursor = "#ebadad"

[colors.search.matches]
foreground = "#1a1a1a"
background = "#844848"

[colors.search.focused_match]
foreground = "#1a1a1a"
background = "#eb4747"

[colors.footer_bar]
foreground = "#1a1a1a"
background = "#844848"

[colors.hints.start]
foreground = "#1a1a1a"
background = "#eb4770"

[colors.hints.end]
foreground = "#1a1a1a"
background = "#844848"

[colors.selection]
text = "#1a1a1a"
background = "#633636"

[colors.normal]
black = "#333333"
red = "#47eb70"
green = "#eb4747"
yellow = "#eb4770"
blue = "#eb7047"
magenta = "#70eb47"
cyan = "#c2eb47"
white = "#ebadad"

[colors.bright]
black = "#333333"
red = "#47eb70"
green = "#eb4747"
yellow = "#eb4770"
blue = "#eb7047"
magenta = "#70eb47"
cyan = "#c2eb47"
white = "#ebadad"

[colors.dim]
black = "#333333"
red = "#47eb70"
green = "#eb4747"
yellow = "#eb4770"
blue = "#eb7047"
magenta = "#70eb47"
cyan = "#c2eb47"
white = "#ebadad"