[colors.primary]
background = "#21212c"
foreground = "#c6e2ec"
dim_foreground = "#82b6c9"
bright_foreground = "#c6e2ec"

[colors.cursor]
text = "#21212c"
cursor = "#c6e2ec"

[colors.vi_mode_cursor]
text = "#21212c"
cursor = "#c6e2ec"

[colors.search.matches]
foreground = "#21212c"
background = "#955095"

[colors.search.focused_match]
foreground = "#21212c"
background = "#c37de8"

[colors.footer_bar]
foreground = "#21212c"
background = "#955095"

[colors.hints.start]
foreground = "#21212c"
background = "#d98cd9"

[colors.hints.end]
foreground = "#21212c"
background = "#955095"

[colors.selection]
text = "#21212c"
background = "#743e74"

[colors.normal]
black = "#373749"
red = "#7db3e8"
green = "#c37de8"
yellow = "#d98cd9"
blue = "#9f7de8"
magenta = "#7de8e8"
cyan = "#82c9b6"
white = "#c6e2ec"

[colors.bright]
black = "#373749"
red = "#7db3e8"
green = "#c37de8"
yellow = "#d98cd9"
blue = "#9f7de8"
magenta = "#7de8e8"
cyan = "#82c9b6"
white = "#c6e2ec"

[colors.dim]
black = "#373749"
red = "#7db3e8"
green = "#c37de8"
yellow = "#d98cd9"
blue = "#9f7de8"
magenta = "#7de8e8"
cyan = "#82c9b6"
white = "#c6e2ec"