[colors.primary]
background = "#d8cde4"
foreground = "#2f0f3d"
dim_foreground = "#66367d"
bright_foreground = "#2f0f3d"

[colors.cursor]
text = "#d8cde4"
cursor = "#2f0f3d"

[colors.vi_mode_cursor]
text = "#d8cde4"
cursor = "#2f0f3d"

[colors.search.matches]
foreground = "#d8cde4"
background = "#6a9baf"

[colors.search.focused_match]
foreground = "#d8cde4"
background = "#6c1b98"

[colors.footer_bar]
foreground = "#d8cde4"
background = "#6a9baf"

[colors.hints.start]
foreground = "#d8cde4"
background = "#981b98"

[colors.hints.end]
foreground = "#d8cde4"
background = "#6a9baf"

[colors.selection]
text = "#d8cde4"
background = "#8bb2c1"

[colors.normal]
black = "#bfacd2"
red = "#1b5998"
green = "#6c1b98"
yellow = "#981b98"
blue = "#421b98"
magenta = "#1b9898"
cyan = "#367d6a"
white = "#2f0f3d"

[colors.bright]
black = "#bfacd2"
red = "#1b5998"
green = "#6c1b98"
yellow = "#981b98"
blue = "#421b98"
magenta = "#1b9898"
cyan = "#367d6a"
white = "#2f0f3d"

[colors.dim]
black = "#bfacd2"
red = "#1b5998"
green = "#6c1b98"
yellow = "#981b98"
blue = "#421b98"
magenta = "#1b9898"
cyan = "#367d6a"
white = "#2f0f3d"