[colors.primary]
background = "#d7cbe7"
foreground = "#230d3f"
dim_foreground = "#543181"
bright_foreground = "#230d3f"

[colors.cursor]
text = "#d7cbe7"
cursor = "#230d3f"

[colors.vi_mode_cursor]
text = "#d7cbe7"
cursor = "#230d3f"

[colors.search.matches]
foreground = "#d7cbe7"
background = "#7070a9"

[colors.search.focused_match]
foreground = "#d7cbe7"
background = "#2e0f8a"

[colors.footer_bar]
foreground = "#d7cbe7"
background = "#7070a9"

[colors.hints.start]
foreground = "#d7cbe7"
background = "#0f2e8a"

[colors.hints.end]
foreground = "#d7cbe7"
background = "#7070a9"

[colors.selection]
text = "#d7cbe7"
background = "#8f8fbc"

[colors.normal]
black = "#bca8d7"
red = "#6b0f8a"
green = "#2e0f8a"
yellow = "#0f2e8a"
blue = "#0f6b8a"
magenta = "#8a0f6b"
cyan = "#8a0f2e"
white = "#230d3f"

[colors.bright]
black = "#bca8d7"
red = "#6b0f8a"
green = "#2e0f8a"
yellow = "#0f2e8a"
blue = "#0f6b8a"
magenta = "#8a0f6b"
cyan = "#8a0f2e"
white = "#230d3f"

[colors.dim]
black = "#bca8d7"
red = "#6b0f8a"
green = "#2e0f8a"
yellow = "#0f2e8a"
blue = "#0f6b8a"
magenta = "#8a0f6b"
cyan = "#8a0f2e"
white = "#230d3f"