[colors.primary]
background = "#262626"
foreground = "#f2c0f2"
dim_foreground = "#ce7ece"
bright_foreground = "#f2c0f2"

[colors.cursor]
text = "#262626"
cursor = "#f2c0f2"

[colors.vi_mode_cursor]
text = "#262626"
cursor = "#f2c0f2"

[colors.search.matches]
foreground = "#262626"
background = "#6f489d"

[colors.search.focused_match]
foreground = "#262626"
background = "#d175f0"

[colors.footer_bar]
foreground = "#262626"
background = "#6f489d"

[colors.hints.start]
foreground = "#262626"
background = "#9475f0"

[colors.hints.end]
foreground = "#262626"
background = "#6f489d"

[colors.selection]
text = "#262626"
background = "#56387a"

[colors.normal]
black = "#404040"
red = "#f075d1"
green = "#d175f0"
yellow = "#9475f0"
blue = "#7594f0"
magenta = "#f07594"
cyan = "#f09275"
white = "#f2c0f2"

[colors.bright]
black = "#404040"
red = "#f075d1"
green = "#d175f0"
yellow = "#9475f0"
blue = "#7594f0"
magenta = "#f07594"
cyan = "#f09275"
white = "#f2c0f2"

[colors.dim]
black = "#404040"
red = "#f075d1"
green = "#d175f0"
yellow = "#9475f0"
blue = "#7594f0"
magenta = "#f07594"
cyan = "#f09275"
white = "#f2c0f2"