[colors.primary]
background = "#262626"
foreground = "#f2c0f2"
dim_foreground = "#ce7ece"
bright_foreground = "#f2c0f2"

[colors.cursor]
text = "#262626"
cursor = "#f2c0f2"

[colors.vi_mode_cursor]
text = "#262626"
cursor = "#f2c0f2"

[colors.search.matches]
foreground = "#262626"
background = "#6f489d"

[colors.search.focused_match]
foreground = "#262626"
background = "#d175f0"

[colors.footer_bar]
foreground = "#262626"
background = "#6f489d"

[colors.hints.start]
foreground = "#262626"
background = "#7594f0"

[colors.hints.end]
foreground = "#262626"
background = "#6f489d"

[colors.selection]
text = "#262626"
background = "#56387a"

[colors.normal]
black = "#333333"
red = "#f075d1"
green = "#d175f0"
yellow = "#f09275"
blue = "#f07594"
magenta = "#7594f0"
cyan = "#9475f0"
white = "#f2c0f2"

[colors.bright]
black = "#404040"
red = "#f5a3e0"
green = "#e0a3f5"
yellow = "#f5b6a3"
blue = "#f5a3b8"
magenta = "#a3b8f5"
cyan = "#b8a3f5"
white = "#ce7ece"

[colors.dim]
black = "#404040"
red = "#f5a3e0"
green = "#e0a3f5"
yellow = "#f5b6a3"
blue = "#f5a3b8"
magenta = "#a3b8f5"
cyan = "#b8a3f5"
white = "#ce7ece"