[colors.primary]
background = "#311b1d"
foreground = "#f0dec2"
dim_foreground = "#c9af82"
bright_foreground = "#f0dec2"

[colors.cursor]
text = "#311b1d"
cursor = "#f0dec2"

[colors.vi_mode_cursor]
text = "#311b1d"
cursor = "#f0dec2"

[colors.search.matches]
foreground = "#311b1d"
background = "#957b50"

[colors.search.focused_match]
foreground = "#311b1d"
background = "#f0d175"

[colors.footer_bar]
foreground = "#311b1d"
background = "#957b50"

[colors.hints.start]
foreground = "#311b1d"
background = "#f0b375"

[colors.hints.end]
foreground = "#311b1d"
background = "#957b50"

[colors.selection]
text = "#311b1d"
background = "#745f3e"

[colors.normal]
black = "#532d30"
red = "#f075f0"
green = "#f0d175"
yellow = "#f0b375"
blue = "#f09475"
magenta = "#f075b3"
cyan = "#f07594"
white = "#f0dec2"

[colors.bright]
black = "#532d30"
red = "#f075f0"
green = "#f0d175"
yellow = "#f0b375"
blue = "#f09475"
magenta = "#f075b3"
cyan = "#f07594"
white = "#f0dec2"

[colors.dim]
black = "#532d30"
red = "#f075f0"
green = "#f0d175"
yellow = "#f0b375"
blue = "#f09475"
magenta = "#f075b3"
cyan = "#f07594"
white = "#f0dec2"