[colors.primary]
background = "#facfb7"
foreground = "#402634"
dim_foreground = "#804d68"
bright_foreground = "#402634"

[colors.cursor]
text = "#facfb7"
cursor = "#402634"

[colors.vi_mode_cursor]
text = "#facfb7"
cursor = "#402634"

[colors.search.matches]
foreground = "#facfb7"
background = "#b3809b"

[colors.search.focused_match]
foreground = "#facfb7"
background = "#921907"

[colors.footer_bar]
foreground = "#facfb7"
background = "#b3809b"

[colors.hints.start]
foreground = "#facfb7"
background = "#997300"

[colors.hints.end]
foreground = "#facfb7"
background = "#b3809b"

[colors.selection]
text = "#facfb7"
background = "#c69fb4"

[colors.normal]
black = "#f8bfa0"
red = "#871252"
green = "#921907"
yellow = "#95043c"
blue = "#123987"
magenta = "#997300"
cyan = "#990099"
white = "#402634"

[colors.bright]
black = "#f7af88"
red = "#b4186e"
green = "#c32209"
yellow = "#c7054f"
blue = "#184cb4"
magenta = "#cc9900"
cyan = "#cc00cc"
white = "#804d68"

[colors.dim]
black = "#f7af88"
red = "#b4186e"
green = "#c32209"
yellow = "#c7054f"
blue = "#184cb4"
magenta = "#cc9900"
cyan = "#cc00cc"
white = "#804d68"