[colors.primary]
background = "#facfb7"
foreground = "#402634"
dim_foreground = "#804d68"
bright_foreground = "#402634"

[colors.cursor]
text = "#facfb7"
cursor = "#402634"

[colors.vi_mode_cursor]
text = "#facfb7"
cursor = "#402634"

[colors.search.matches]
foreground = "#facfb7"
background = "#b3809b"

[colors.search.focused_match]
foreground = "#facfb7"
background = "#921907"

[colors.footer_bar]
foreground = "#facfb7"
background = "#b3809b"

[colors.hints.start]
foreground = "#facfb7"
background = "#990099"

[colors.hints.end]
foreground = "#facfb7"
background = "#b3809b"

[colors.selection]
text = "#facfb7"
background = "#c69fb4"

[colors.normal]
black = "#f7af88"
red = "#871252"
green = "#921907"
yellow = "#990099"
blue = "#997300"
magenta = "#123987"
cyan = "#95043c"
white = "#402634"

[colors.bright]
black = "#f7af88"
red = "#871252"
green = "#921907"
yellow = "#990099"
blue = "#997300"
magenta = "#123987"
cyan = "#95043c"
white = "#402634"

[colors.dim]
black = "#f7af88"
red = "#871252"
green = "#921907"
yellow = "#990099"
blue = "#997300"
magenta = "#123987"
cyan = "#95043c"
white = "#402634"