[colors.primary]
background = "#251a33"
foreground = "#f0c2c2"
dim_foreground = "#c98282"
bright_foreground = "#f0c2c2"

[colors.cursor]
text = "#251a33"
cursor = "#f0c2c2"

[colors.vi_mode_cursor]
text = "#251a33"
cursor = "#f0c2c2"

[colors.search.matches]
foreground = "#251a33"
background = "#974e60"

[colors.search.focused_match]
foreground = "#251a33"
background = "#9475f0"

[colors.footer_bar]
foreground = "#251a33"
background = "#974e60"

[colors.hints.start]
foreground = "#251a33"
background = "#f075d1"

[colors.hints.end]
foreground = "#251a33"
background = "#974e60"

[colors.selection]
text = "#251a33"
background = "#763d4b"

[colors.normal]
black = "#312343"
red = "#7594f0"
green = "#9475f0"
yellow = "#f07594"
blue = "#f09475"
magenta = "#f075d1"
cyan = "#d175f0"
white = "#f0c2c2"

[colors.bright]
black = "#3d2b54"
red = "#a3b8f5"
green = "#b8a3f5"
yellow = "#f5a3b8"
blue = "#f5b8a3"
magenta = "#f5a3e0"
cyan = "#e0a3f5"
white = "#c98282"

[colors.dim]
black = "#3d2b54"
red = "#a3b8f5"
green = "#b8a3f5"
yellow = "#f5a3b8"
blue = "#f5b8a3"
magenta = "#f5a3e0"
cyan = "#e0a3f5"
white = "#c98282"