[colors.primary]
background = "#251a33"
foreground = "#f0c2c2"
dim_foreground = "#c98282"
bright_foreground = "#f0c2c2"

[colors.cursor]
text = "#251a33"
cursor = "#f0c2c2"

[colors.vi_mode_cursor]
text = "#251a33"
cursor = "#f0c2c2"

[colors.search.matches]
foreground = "#251a33"
background = "#974e60"

[colors.search.focused_match]
foreground = "#251a33"
background = "#9475f0"

[colors.footer_bar]
foreground = "#251a33"
background = "#974e60"

[colors.hints.start]
foreground = "#251a33"
background = "#d175f0"

[colors.hints.end]
foreground = "#251a33"
background = "#974e60"

[colors.selection]
text = "#251a33"
background = "#763d4b"

[colors.normal]
black = "#3d2b54"
red = "#7594f0"
green = "#9475f0"
yellow = "#d175f0"
blue = "#f075d1"
magenta = "#f09475"
cyan = "#f07594"
white = "#f0c2c2"

[colors.bright]
black = "#3d2b54"
red = "#7594f0"
green = "#9475f0"
yellow = "#d175f0"
blue = "#f075d1"
magenta = "#f09475"
cyan = "#f07594"
white = "#f0c2c2"

[colors.dim]
black = "#3d2b54"
red = "#7594f0"
green = "#9475f0"
yellow = "#d175f0"
blue = "#f075d1"
magenta = "#f09475"
cyan = "#f07594"
white = "#f0c2c2"