[colors.primary]
background = "#e4cdd0"
foreground = "#3d0f25"
dim_foreground = "#7d3657"
bright_foreground = "#3d0f25"

[colors.cursor]
text = "#e4cdd0"
cursor = "#3d0f25"

[colors.vi_mode_cursor]
text = "#e4cdd0"
cursor = "#3d0f25"

[colors.search.matches]
foreground = "#e4cdd0"
background = "#af6a8a"

[colors.search.focused_match]
foreground = "#e4cdd0"
background = "#8f2457"

[colors.footer_bar]
foreground = "#e4cdd0"
background = "#af6a8a"

[colors.hints.start]
foreground = "#e4cdd0"
background = "#931f1f"

[colors.hints.end]
foreground = "#e4cdd0"
background = "#af6a8a"

[colors.selection]
text = "#e4cdd0"
background = "#c18ba4"

[colors.normal]
black = "#d2acb1"
red = "#2d2d86"
green = "#8f2457"
yellow = "#931f1f"
blue = "#983a1b"
magenta = "#59248f"
cyan = "#862d86"
white = "#3d0f25"

[colors.bright]
black = "#d2acb1"
red = "#2d2d86"
green = "#8f2457"
yellow = "#931f1f"
blue = "#983a1b"
magenta = "#59248f"
cyan = "#862d86"
white = "#3d0f25"

[colors.dim]
black = "#d2acb1"
red = "#2d2d86"
green = "#8f2457"
yellow = "#931f1f"
blue = "#983a1b"
magenta = "#59248f"
cyan = "#862d86"
white = "#3d0f25"