[colors.primary]
background = "#2f1d25"
foreground = "#f0c2c2"
dim_foreground = "#c98282"
bright_foreground = "#f0c2c2"

[colors.cursor]
text = "#2f1d25"
cursor = "#f0c2c2"

[colors.vi_mode_cursor]
text = "#2f1d25"
cursor = "#f0c2c2"

[colors.search.matches]
foreground = "#2f1d25"
background = "#945151"

[colors.search.focused_match]
foreground = "#2f1d25"
background = "#e87db1"

[colors.footer_bar]
foreground = "#2f1d25"
background = "#945151"

[colors.hints.start]
foreground = "#2f1d25"
background = "#e87d7d"

[colors.hints.end]
foreground = "#2f1d25"
background = "#945151"

[colors.selection]
text = "#2f1d25"
background = "#733f3f"

[colors.normal]
black = "#4f303e"
red = "#7d7de8"
green = "#e87db1"
yellow = "#e87d7d"
blue = "#e8987d"
magenta = "#b37de8"
cyan = "#e085e0"
white = "#f0c2c2"

[colors.bright]
black = "#4f303e"
red = "#7d7de8"
green = "#e87db1"
yellow = "#e87d7d"
blue = "#e8987d"
magenta = "#b37de8"
cyan = "#e085e0"
white = "#f0c2c2"

[colors.dim]
black = "#4f303e"
red = "#7d7de8"
green = "#e87db1"
yellow = "#e87d7d"
blue = "#e8987d"
magenta = "#b37de8"
cyan = "#e085e0"
white = "#f0c2c2"