[colors.primary]
background = "#262626"
foreground = "#ffffff"
dim_foreground = "#bfbfbf"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#262626"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#262626"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#262626"
background = "#b8732e"

[colors.search.focused_match]
foreground = "#262626"
background = "#ffb366"

[colors.footer_bar]
foreground = "#262626"
background = "#b8732e"

[colors.hints.start]
foreground = "#262626"
background = "#ffd966"

[colors.hints.end]
foreground = "#262626"
background = "#b8732e"

[colors.selection]
text = "#262626"
background = "#8f5924"

[colors.normal]
black = "#404040"
red = "#ff668c"
green = "#ffb366"
yellow = "#ffd966"
blue = "#ffff66"
magenta = "#ff6666"
cyan = "#ff8c66"
white = "#ffffff"

[colors.bright]
black = "#404040"
red = "#ff668c"
green = "#ffb366"
yellow = "#ffd966"
blue = "#ffff66"
magenta = "#ff6666"
cyan = "#ff8c66"
white = "#ffffff"

[colors.dim]
black = "#404040"
red = "#ff668c"
green = "#ffb366"
yellow = "#ffd966"
blue = "#ffff66"
magenta = "#ff6666"
cyan = "#ff8c66"
white = "#ffffff"