[colors.primary]
background = "#e4cde2"
foreground = "#230f3d"
dim_foreground = "#54367d"
bright_foreground = "#230f3d"

[colors.cursor]
text = "#e4cde2"
cursor = "#230f3d"

[colors.vi_mode_cursor]
text = "#e4cde2"
cursor = "#230f3d"

[colors.search.matches]
foreground = "#e4cde2"
background = "#75a398"

[colors.search.focused_match]
foreground = "#e4cde2"
background = "#1f7a4d"

[colors.footer_bar]
foreground = "#e4cde2"
background = "#75a398"

[colors.hints.start]
foreground = "#e4cde2"
background = "#1b7e7e"

[colors.hints.end]
foreground = "#e4cde2"
background = "#75a398"

[colors.selection]
text = "#e4cde2"
background = "#94b8af"

[colors.normal]
black = "#d2accf"
red = "#7e7e1b"
green = "#1f7a4d"
yellow = "#1b7e7e"
blue = "#1f5993"
magenta = "#93591f"
cyan = "#8a6b0f"
white = "#230f3d"

[colors.bright]
black = "#d2accf"
red = "#7e7e1b"
green = "#1f7a4d"
yellow = "#1b7e7e"
blue = "#1f5993"
magenta = "#93591f"
cyan = "#8a6b0f"
white = "#230f3d"

[colors.dim]
black = "#d2accf"
red = "#7e7e1b"
green = "#1f7a4d"
yellow = "#1b7e7e"
blue = "#1f5993"
magenta = "#93591f"
cyan = "#8a6b0f"
white = "#230f3d"