[colors.primary]
background = "#301d2e"
foreground = "#f0e3c2"
dim_foreground = "#c9b682"
bright_foreground = "#f0e3c2"

[colors.cursor]
text = "#301d2e"
cursor = "#f0e3c2"

[colors.vi_mode_cursor]
text = "#301d2e"
cursor = "#f0e3c2"

[colors.search.matches]
foreground = "#301d2e"
background = "#5c8a7e"

[colors.search.focused_match]
foreground = "#301d2e"
background = "#7de8b3"

[colors.footer_bar]
foreground = "#301d2e"
background = "#5c8a7e"

[colors.hints.start]
foreground = "#301d2e"
background = "#7de8e8"

[colors.hints.end]
foreground = "#301d2e"
background = "#5c8a7e"

[colors.selection]
text = "#301d2e"
background = "#476b62"

[colors.normal]
black = "#50304d"
red = "#ecec79"
green = "#7de8b3"
yellow = "#7de8e8"
blue = "#7db3e8"
magenta = "#ecb379"
cyan = "#f0d175"
white = "#f0e3c2"

[colors.bright]
black = "#50304d"
red = "#ecec79"
green = "#7de8b3"
yellow = "#7de8e8"
blue = "#7db3e8"
magenta = "#ecb379"
cyan = "#f0d175"
white = "#f0e3c2"

[colors.dim]
black = "#50304d"
red = "#ecec79"
green = "#7de8b3"
yellow = "#7de8e8"
blue = "#7db3e8"
magenta = "#ecb379"
cyan = "#f0d175"
white = "#f0e3c2"