[colors.primary]
background = "#ece7df"
foreground = "#364c7d"
dim_foreground = "#5e7bba"
bright_foreground = "#364c7d"

[colors.cursor]
text = "#ece7df"
cursor = "#364c7d"

[colors.vi_mode_cursor]
text = "#ece7df"
cursor = "#364c7d"

[colors.search.matches]
foreground = "#ece7df"
background = "#98aacd"

[colors.search.focused_match]
foreground = "#ece7df"
background = "#15829d"

[colors.footer_bar]
foreground = "#ece7df"
background = "#98aacd"

[colors.hints.start]
foreground = "#ece7df"
background = "#957104"

[colors.hints.end]
foreground = "#ece7df"
background = "#98aacd"

[colors.selection]
text = "#ece7df"
background = "#adbad2"

[colors.normal]
black = "#d4cec4"
red = "#7d363d"
green = "#15829d"
yellow = "#957104"
blue = "#b05903"
magenta = "#36567d"
cyan = "#951d27"
white = "#364c7d"

[colors.bright]
black = "#d4cec4"
red = "#7d363d"
green = "#15829d"
yellow = "#957104"
blue = "#b05903"
magenta = "#36567d"
cyan = "#951d27"
white = "#364c7d"

[colors.dim]
black = "#d4cec4"
red = "#7d363d"
green = "#15829d"
yellow = "#957104"
blue = "#b05903"
magenta = "#36567d"
cyan = "#951d27"
white = "#364c7d"