[colors.primary]
background = "#3d7d8f"
foreground = "#fef6cd"
dim_foreground = "#f5e38a"
bright_foreground = "#fef6cd"

[colors.cursor]
text = "#3d7d8f"
cursor = "#fef6cd"

[colors.vi_mode_cursor]
text = "#3d7d8f"
cursor = "#fef6cd"

[colors.search.matches]
foreground = "#3d7d8f"
background = "#365963"

[colors.search.focused_match]
foreground = "#3d7d8f"
background = "#adbad2"

[colors.footer_bar]
foreground = "#3d7d8f"
background = "#365963"

[colors.hints.start]
foreground = "#3d7d8f"
background = "#ddcba2"

[colors.hints.end]
foreground = "#3d7d8f"
background = "#365963"

[colors.selection]
text = "#3d7d8f"
background = "#3a6a78"

[colors.normal]
black = "#4d9cb3"
red = "#eb939e"
green = "#adbad2"
yellow = "#ddcba2"
blue = "#f9bf85"
magenta = "#cacbce"
cyan = "#86e4f9"
white = "#fef6cd"

[colors.bright]
black = "#4d9cb3"
red = "#eb939e"
green = "#adbad2"
yellow = "#ddcba2"
blue = "#f9bf85"
magenta = "#cacbce"
cyan = "#86e4f9"
white = "#fef6cd"

[colors.dim]
black = "#4d9cb3"
red = "#eb939e"
green = "#adbad2"
yellow = "#ddcba2"
blue = "#f9bf85"
magenta = "#cacbce"
cyan = "#86e4f9"
white = "#fef6cd"