[colors.primary]
background = "#1b3132"
foreground = "#f0c2cd"
dim_foreground = "#c98294"
bright_foreground = "#f0c2cd"

[colors.cursor]
text = "#1b3132"
cursor = "#f0c2cd"

[colors.vi_mode_cursor]
text = "#1b3132"
cursor = "#f0c2cd"

[colors.search.matches]
foreground = "#1b3132"
background = "#509295"

[colors.search.focused_match]
foreground = "#1b3132"
background = "#e87d7d"

[colors.footer_bar]
foreground = "#1b3132"
background = "#509295"

[colors.hints.start]
foreground = "#1b3132"
background = "#e87db3"

[colors.hints.end]
foreground = "#1b3132"
background = "#509295"

[colors.selection]
text = "#1b3132"
background = "#3e7174"

[colors.normal]
black = "#2d5153"
red = "#7db3e8"
green = "#e87d7d"
yellow = "#e87db3"
blue = "#e87de8"
magenta = "#7d7de8"
cyan = "#b37de8"
white = "#f0c2cd"

[colors.bright]
black = "#2d5153"
red = "#7db3e8"
green = "#e87d7d"
yellow = "#e87db3"
blue = "#e87de8"
magenta = "#7d7de8"
cyan = "#b37de8"
white = "#f0c2cd"

[colors.dim]
black = "#2d5153"
red = "#7db3e8"
green = "#e87d7d"
yellow = "#e87db3"
blue = "#e87de8"
magenta = "#7d7de8"
cyan = "#b37de8"
white = "#f0c2cd"