[colors.primary]
background = "#cdcde4"
foreground = "#0f1e3d"
dim_foreground = "#364b7d"
bright_foreground = "#0f1e3d"

[colors.cursor]
text = "#cdcde4"
cursor = "#0f1e3d"

[colors.vi_mode_cursor]
text = "#cdcde4"
cursor = "#0f1e3d"

[colors.search.matches]
foreground = "#cdcde4"
background = "#6a7caf"

[colors.search.focused_match]
foreground = "#cdcde4"
background = "#2d4386"

[colors.footer_bar]
foreground = "#cdcde4"
background = "#6a7caf"

[colors.hints.start]
foreground = "#cdcde4"
background = "#24748f"

[colors.hints.end]
foreground = "#cdcde4"
background = "#6a7caf"

[colors.selection]
text = "#cdcde4"
background = "#8b99c1"

[colors.normal]
black = "#acacd2"
red = "#862d86"
green = "#2d4386"
yellow = "#24748f"
blue = "#3e248f"
magenta = "#8e2559"
cyan = "#862d2d"
white = "#0f1e3d"

[colors.bright]
black = "#acacd2"
red = "#862d86"
green = "#2d4386"
yellow = "#24748f"
blue = "#3e248f"
magenta = "#8e2559"
cyan = "#862d2d"
white = "#0f1e3d"

[colors.dim]
black = "#acacd2"
red = "#862d86"
green = "#2d4386"
yellow = "#24748f"
blue = "#3e248f"
magenta = "#8e2559"
cyan = "#862d2d"
white = "#0f1e3d"