[colors.primary]
background = "#22222b"
foreground = "#f0c2dd"
dim_foreground = "#c982ad"
bright_foreground = "#f0c2dd"

[colors.cursor]
text = "#22222b"
cursor = "#f0c2dd"

[colors.vi_mode_cursor]
text = "#22222b"
cursor = "#f0c2dd"

[colors.search.matches]
foreground = "#22222b"
background = "#95507a"

[colors.search.focused_match]
foreground = "#22222b"
background = "#7171f4"

[colors.footer_bar]
foreground = "#22222b"
background = "#95507a"

[colors.hints.start]
foreground = "#22222b"
background = "#71f4f4"

[colors.hints.end]
foreground = "#22222b"
background = "#95507a"

[colors.selection]
text = "#22222b"
background = "#743e5f"

[colors.normal]
black = "#383847"
red = "#d966ff"
green = "#7171f4"
yellow = "#71f4f4"
blue = "#66ccff"
magenta = "#8cb3d9"
cyan = "#b366ff"
white = "#f0c2dd"

[colors.bright]
black = "#383847"
red = "#d966ff"
green = "#7171f4"
yellow = "#71f4f4"
blue = "#66ccff"
magenta = "#8cb3d9"
cyan = "#b366ff"
white = "#f0c2dd"

[colors.dim]
black = "#383847"
red = "#d966ff"
green = "#7171f4"
yellow = "#71f4f4"
blue = "#66ccff"
magenta = "#8cb3d9"
cyan = "#b366ff"
white = "#f0c2dd"