[colors.primary]
background = "#22222b"
foreground = "#c2ecf0"
dim_foreground = "#82c3c9"
bright_foreground = "#c2ecf0"

[colors.cursor]
text = "#22222b"
cursor = "#c2ecf0"

[colors.vi_mode_cursor]
text = "#22222b"
cursor = "#c2ecf0"

[colors.search.matches]
foreground = "#22222b"
background = "#508f95"

[colors.search.focused_match]
foreground = "#22222b"
background = "#7171f4"

[colors.footer_bar]
foreground = "#22222b"
background = "#508f95"

[colors.hints.start]
foreground = "#22222b"
background = "#71f4f4"

[colors.hints.end]
foreground = "#22222b"
background = "#508f95"

[colors.selection]
text = "#22222b"
background = "#3e7074"

[colors.normal]
black = "#383847"
red = "#d966ff"
green = "#7171f4"
yellow = "#71f4f4"
blue = "#66ccff"
magenta = "#8cb3d9"
cyan = "#b366ff"
white = "#c2ecf0"

[colors.bright]
black = "#383847"
red = "#d966ff"
green = "#7171f4"
yellow = "#71f4f4"
blue = "#66ccff"
magenta = "#8cb3d9"
cyan = "#b366ff"
white = "#c2ecf0"

[colors.dim]
black = "#383847"
red = "#d966ff"
green = "#7171f4"
yellow = "#71f4f4"
blue = "#66ccff"
magenta = "#8cb3d9"
cyan = "#b366ff"
white = "#c2ecf0"