[colors.primary]
background = "#262626"
foreground = "#f0c2d0"
dim_foreground = "#c98299"
bright_foreground = "#f0c2d0"

[colors.cursor]
text = "#262626"
cursor = "#f0c2d0"

[colors.vi_mode_cursor]
text = "#262626"
cursor = "#f0c2d0"

[colors.search.matches]
foreground = "#262626"
background = "#955066"

[colors.search.focused_match]
foreground = "#262626"
background = "#e87db3"

[colors.footer_bar]
foreground = "#262626"
background = "#955066"

[colors.hints.start]
foreground = "#262626"
background = "#e8987d"

[colors.hints.end]
foreground = "#262626"
background = "#955066"

[colors.selection]
text = "#262626"
background = "#743e4f"

[colors.normal]
black = "#404040"
red = "#7d7de8"
green = "#e87db3"
yellow = "#e8987d"
blue = "#e87d7d"
magenta = "#e87de8"
cyan = "#b37de8"
white = "#f0c2d0"

[colors.bright]
black = "#404040"
red = "#7d7de8"
green = "#e87db3"
yellow = "#e8987d"
blue = "#e87d7d"
magenta = "#e87de8"
cyan = "#b37de8"
white = "#f0c2d0"

[colors.dim]
black = "#404040"
red = "#7d7de8"
green = "#e87db3"
yellow = "#e8987d"
blue = "#e87d7d"
magenta = "#e87de8"
cyan = "#b37de8"
white = "#f0c2d0"