[colors.primary]
background = "#2c2321"
foreground = "#f0c6c2"
dim_foreground = "#c98982"
bright_foreground = "#f0c6c2"

[colors.cursor]
text = "#2c2321"
cursor = "#f0c6c2"

[colors.vi_mode_cursor]
text = "#2c2321"
cursor = "#f0c6c2"

[colors.search.matches]
foreground = "#2c2321"
background = "#955750"

[colors.search.focused_match]
foreground = "#2c2321"
background = "#f76e6e"

[colors.footer_bar]
foreground = "#2c2321"
background = "#955750"

[colors.hints.start]
foreground = "#2c2321"
background = "#f76eb3"

[colors.hints.end]
foreground = "#2c2321"
background = "#955750"

[colors.selection]
text = "#2c2321"
background = "#74433e"

[colors.normal]
black = "#3a2e2c"
red = "#f7d56e"
green = "#f76e6e"
yellow = "#f7906e"
blue = "#f7b36e"
magenta = "#f76eb3"
cyan = "#f76e90"
white = "#f0c6c2"

[colors.bright]
black = "#493a37"
red = "#fae39e"
green = "#fa9e9e"
yellow = "#fab59e"
blue = "#facc9e"
magenta = "#fa9ecc"
cyan = "#fa9eb5"
white = "#c98982"

[colors.dim]
black = "#493a37"
red = "#fae39e"
green = "#fa9e9e"
yellow = "#fab59e"
blue = "#facc9e"
magenta = "#fa9ecc"
cyan = "#fa9eb5"
white = "#c98982"