[colors.primary]
background = "BackGround1"
foreground = "ForeGround1"
dim_foreground = "ForeGround3"
bright_foreground = "ForeGround1"

[colors.cursor]
text = "BackGround1"
cursor = "ForeGround1"

[colors.vi_mode_cursor]
text = "BackGround1"
cursor = "ForeGround1"

[colors.search.matches]
foreground = "BackGround1"
background = "HighLight2"

[colors.search.focused_match]
foreground = "BackGround1"
background = "Syn4"

[colors.footer_bar]
foreground = "BackGround1"
background = "HighLight2"

[colors.hints.start]
foreground = "BackGround1"
background = "Syn2"

[colors.hints.end]
foreground = "BackGround1"
background = "HighLight2"

[colors.selection]
text = "BackGround1"
background = "HighLight3"

[colors.normal]
black = "BackGround3"
red = "Syn1"
green = "Syn4"
yellow = "Syn2"
blue = "Syn5"
magenta = "Syn6"
cyan = "Syn3"
white = "ForeGround1"

[colors.bright]
black = "BackGround3"
red = "Syn1"
green = "Syn4"
yellow = "Syn2"
blue = "Syn5"
magenta = "Syn6"
cyan = "Syn3"
white = "ForeGround1"

[colors.dim]
black = "BackGround3"
red = "Syn1"
green = "Syn4"
yellow = "Syn2"
blue = "Syn5"
magenta = "Syn6"
cyan = "Syn3"
white = "ForeGround1"